package it.almavivaitalia.bilancio.commons.to;

// Generated 9-lug-2010 17.37.06 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * EserciziTO generated by hbm2java
 */
public class EserciziTO extends AbstractCommonTO implements java.io.Serializable {//INIZIO METODO

	private Short id;
	private String statTipoEse;
	private String statStatus;
	private String statFibc;
	private Date dataPresdlb;
	private Date dataApprdlb;
	private Date dataAperdlf;
	private Date dataPresdlf;
	private Date dataApprdlf;
	private Integer numeLegvig;
	private Date dataFineincl;
	private Integer flagEntrate01;
	private Integer flagProp01;
	private Integer flagIbe01;
	private Integer flagRev201;
	private Integer flagRev101;
	private Short numeDlbPres;
	private String codiTipoattoEmer;
	private Date dataEsclDmc;

	public EserciziTO() {//INIZIO METODO
	}

	public EserciziTO(String statTipoEse, String statStatus, Integer numeLegvig) {//INIZIO METODO
		this.statTipoEse = statTipoEse;
		this.statStatus = statStatus;
		this.numeLegvig = numeLegvig;
	}

	public Short getId() {//INIZIO METODO
		return this.id;
	}

	public void setId(Short id) {//INIZIO METODO
		this.id = id;
	}

	public String getStatTipoEse() {//INIZIO METODO
		return this.statTipoEse;
	}

	public void setStatTipoEse(String statTipoEse) {//INIZIO METODO
		this.statTipoEse = statTipoEse;
	}

	public String getStatStatus() {//INIZIO METODO
		return this.statStatus;
	}

	public void setStatStatus(String statStatus) {//INIZIO METODO
		this.statStatus = statStatus;
	}

	public Date getDataPresdlb() {//INIZIO METODO
		return this.dataPresdlb;
	}

	public void setDataPresdlb(Date dataPresdlb) {//INIZIO METODO
		this.dataPresdlb = dataPresdlb;
	}

	public Date getDataApprdlb() {//INIZIO METODO
		return this.dataApprdlb;
	}

	public void setDataApprdlb(Date dataApprdlb) {//INIZIO METODO
		this.dataApprdlb = dataApprdlb;
	}

	public Date getDataAperdlf() {//INIZIO METODO
		return this.dataAperdlf;
	}

	public void setDataAperdlf(Date dataAperdlf) {//INIZIO METODO
		this.dataAperdlf = dataAperdlf;
	}

	public Date getDataPresdlf() {//INIZIO METODO
		return this.dataPresdlf;
	}

	public void setDataPresdlf(Date dataPresdlf) {//INIZIO METODO
		this.dataPresdlf = dataPresdlf;
	}

	public Date getDataApprdlf() {//INIZIO METODO
		return this.dataApprdlf;
	}

	public void setDataApprdlf(Date dataApprdlf) {//INIZIO METODO
		this.dataApprdlf = dataApprdlf;
	}

	public Integer getNumeLegvig() {//INIZIO METODO
		return this.numeLegvig;
	}

	public void setNumeLegvig(Integer numeLegvig) {//INIZIO METODO
		this.numeLegvig = numeLegvig;
	}

	public Date getDataFineincl() {//INIZIO METODO
		return this.dataFineincl;
	}

	public void setDataFineincl(Date dataFineincl) {//INIZIO METODO
		this.dataFineincl = dataFineincl;
	}

	public Integer getFlagEntrate01() {//INIZIO METODO
		return this.flagEntrate01;
	}

	public void setFlagEntrate01(Integer flagEntrate01) {//INIZIO METODO
		this.flagEntrate01 = flagEntrate01;
	}

	public Integer getFlagProp01() {//INIZIO METODO
		return this.flagProp01;
	}

	public void setFlagProp01(Integer flagProp01) {//INIZIO METODO
		this.flagProp01 = flagProp01;
	}

	public Integer getFlagIbe01() {//INIZIO METODO
		return this.flagIbe01;
	}

	public void setFlagIbe01(Integer flagIbe01) {//INIZIO METODO
		this.flagIbe01 = flagIbe01;
	}

	public Integer getFlagRev201() {//INIZIO METODO
		return this.flagRev201;
	}

	public void setFlagRev201(Integer flagRev201) {//INIZIO METODO
		this.flagRev201 = flagRev201;
	}

	public Integer getFlagRev101() {//INIZIO METODO
		return this.flagRev101;
	}

	public void setFlagRev101(Integer flagRev101) {//INIZIO METODO
		this.flagRev101 = flagRev101;
	}
	
	public String getStatFibc() {
		return statFibc;
	}

	public void setStatFibc(String statFibc) {
		this.statFibc = statFibc;
	}	

	public Short getNumeDlbPres() {//INIZIO METODO
		return this.numeDlbPres;
	}

	public void setNumeDlbPres(Short numeDlbPres) {//INIZIO METODO
		this.numeDlbPres = numeDlbPres;
	}

	public String getCodiTipoattoEmer() {//INIZIO METODO
		return this.codiTipoattoEmer;
	}

	public void setCodiTipoattoEmer(String codiTipoattoEmer) {//INIZIO METODO
		this.codiTipoattoEmer = codiTipoattoEmer;
	}

	public Date getDataEsclDmc() {//INIZIO METODO
		return this.dataEsclDmc;
	}

	public void setDataEsclDmc(Date dataEsclDmc) {//INIZIO METODO
		this.dataEsclDmc = dataEsclDmc;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {//INIZIO METODO
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(
				Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("statTipoEse").append("='").append(getStatTipoEse())
				.append("' ");
		buffer.append("statStatus").append("='").append(getStatStatus())
				.append("' ");
		buffer.append("statFibc").append("='").append(getStatFibc())
				.append("' ");		
		buffer.append("dataPresdlb").append("='").append(getDataPresdlb())
				.append("' ");
		buffer.append("dataApprdlb").append("='").append(getDataApprdlb())
				.append("' ");
		buffer.append("dataAperdlf").append("='").append(getDataAperdlf())
				.append("' ");
		buffer.append("dataPresdlf").append("='").append(getDataPresdlf())
				.append("' ");
		buffer.append("dataApprdlf").append("='").append(getDataApprdlf())
				.append("' ");
		buffer.append("numeLegvig").append("='").append(getNumeLegvig())
				.append("' ");
		buffer.append("dataFineincl").append("='").append(getDataFineincl())
				.append("' ");
		buffer.append("flagEntrate01").append("='").append(getFlagEntrate01())
				.append("' ");
		buffer.append("flagProp01").append("='").append(getFlagProp01())
				.append("' ");
		buffer.append("flagIbe01").append("='").append(getFlagIbe01()).append(
				"' ");
		buffer.append("flagRev201").append("='").append(getFlagRev201())
				.append("' ");
		buffer.append("flagRev101").append("='").append(getFlagRev101())
				.append("' ");
		buffer.append("numeDlbPres").append("='").append(getNumeDlbPres())
				.append("' ");
		buffer.append("codiTipoattoEmer").append("='").append(
				getCodiTipoattoEmer()).append("' ");
		buffer.append("dataEsclDmc").append("='").append(getDataEsclDmc())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {//INIZIO METODO
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EserciziTO))
			return false;
		EserciziTO castOther = (EserciziTO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getStatTipoEse() == castOther.getStatTipoEse()) || (this
						.getStatTipoEse() != null
						&& castOther.getStatTipoEse() != null && this
						.getStatTipoEse().equals(castOther.getStatTipoEse())))
				&& ((this.getStatStatus() == castOther.getStatStatus()) || (this
						.getStatStatus() != null
						&& castOther.getStatStatus() != null && this
						.getStatStatus().equals(castOther.getStatStatus())))
				&& ((this.getStatFibc() == castOther.getStatFibc()) || (this
						.getStatFibc() != null
						&& castOther.getStatFibc() != null && this
						.getStatFibc().equals(castOther.getStatFibc())))						
				&& ((this.getDataPresdlb() == castOther.getDataPresdlb()) || (this
						.getDataPresdlb() != null
						&& castOther.getDataPresdlb() != null && this
						.getDataPresdlb().equals(castOther.getDataPresdlb())))
				&& ((this.getDataApprdlb() == castOther.getDataApprdlb()) || (this
						.getDataApprdlb() != null
						&& castOther.getDataApprdlb() != null && this
						.getDataApprdlb().equals(castOther.getDataApprdlb())))
				&& ((this.getDataAperdlf() == castOther.getDataAperdlf()) || (this
						.getDataAperdlf() != null
						&& castOther.getDataAperdlf() != null && this
						.getDataAperdlf().equals(castOther.getDataAperdlf())))
				&& ((this.getDataPresdlf() == castOther.getDataPresdlf()) || (this
						.getDataPresdlf() != null
						&& castOther.getDataPresdlf() != null && this
						.getDataPresdlf().equals(castOther.getDataPresdlf())))
				&& ((this.getDataApprdlf() == castOther.getDataApprdlf()) || (this
						.getDataApprdlf() != null
						&& castOther.getDataApprdlf() != null && this
						.getDataApprdlf().equals(castOther.getDataApprdlf())))
				&& ((this.getNumeLegvig() == castOther.getNumeLegvig()) || (this
						.getNumeLegvig() != null
						&& castOther.getNumeLegvig() != null && this
						.getNumeLegvig().equals(castOther.getNumeLegvig())))
				&& ((this.getDataFineincl() == castOther.getDataFineincl()) || (this
						.getDataFineincl() != null
						&& castOther.getDataFineincl() != null && this
						.getDataFineincl().equals(castOther.getDataFineincl())))
				&& ((this.getFlagEntrate01() == castOther.getFlagEntrate01()) || (this
						.getFlagEntrate01() != null
						&& castOther.getFlagEntrate01() != null && this
						.getFlagEntrate01()
						.equals(castOther.getFlagEntrate01())))
				&& ((this.getFlagProp01() == castOther.getFlagProp01()) || (this
						.getFlagProp01() != null
						&& castOther.getFlagProp01() != null && this
						.getFlagProp01().equals(castOther.getFlagProp01())))
				&& ((this.getFlagIbe01() == castOther.getFlagIbe01()) || (this
						.getFlagIbe01() != null
						&& castOther.getFlagIbe01() != null && this
						.getFlagIbe01().equals(castOther.getFlagIbe01())))
				&& ((this.getFlagRev201() == castOther.getFlagRev201()) || (this
						.getFlagRev201() != null
						&& castOther.getFlagRev201() != null && this
						.getFlagRev201().equals(castOther.getFlagRev201())))
				&& ((this.getFlagRev101() == castOther.getFlagRev101()) || (this
						.getFlagRev101() != null
						&& castOther.getFlagRev101() != null && this
						.getFlagRev101().equals(castOther.getFlagRev101())))
				&& ((this.getNumeDlbPres() == castOther.getNumeDlbPres()) || (this
						.getNumeDlbPres() != null
						&& castOther.getNumeDlbPres() != null && this
						.getNumeDlbPres().equals(castOther.getNumeDlbPres())))
				&& ((this.getCodiTipoattoEmer() == castOther
						.getCodiTipoattoEmer()) || (this.getCodiTipoattoEmer() != null
						&& castOther.getCodiTipoattoEmer() != null && this
						.getCodiTipoattoEmer().equals(
								castOther.getCodiTipoattoEmer())))
				&& ((this.getDataEsclDmc() == castOther.getDataEsclDmc()) || (this
						.getDataEsclDmc() != null
						&& castOther.getDataEsclDmc() != null && this
						.getDataEsclDmc().equals(castOther.getDataEsclDmc())));
	}

	public int hashCode() {//INIZIO METODO
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getStatTipoEse() == null ? 0 : this.getStatTipoEse()
						.hashCode());
		result = 37
				* result
				+ (getStatStatus() == null ? 0 : this.getStatStatus()
						.hashCode());
		result = 37
				* result
				+ (getStatFibc() == null ? 0 : this.getStatFibc()
						.hashCode());			
		result = 37
				* result
				+ (getDataPresdlb() == null ? 0 : this.getDataPresdlb()
						.hashCode());
		result = 37
				* result
				+ (getDataApprdlb() == null ? 0 : this.getDataApprdlb()
						.hashCode());
		result = 37
				* result
				+ (getDataAperdlf() == null ? 0 : this.getDataAperdlf()
						.hashCode());
		result = 37
				* result
				+ (getDataPresdlf() == null ? 0 : this.getDataPresdlf()
						.hashCode());
		result = 37
				* result
				+ (getDataApprdlf() == null ? 0 : this.getDataApprdlf()
						.hashCode());
		result = 37
				* result
				+ (getNumeLegvig() == null ? 0 : this.getNumeLegvig()
						.hashCode());
		result = 37
				* result
				+ (getDataFineincl() == null ? 0 : this.getDataFineincl()
						.hashCode());
		result = 37
				* result
				+ (getFlagEntrate01() == null ? 0 : this.getFlagEntrate01()
						.hashCode());
		result = 37
				* result
				+ (getFlagProp01() == null ? 0 : this.getFlagProp01()
						.hashCode());
		result = 37 * result
				+ (getFlagIbe01() == null ? 0 : this.getFlagIbe01().hashCode());
		result = 37
				* result
				+ (getFlagRev201() == null ? 0 : this.getFlagRev201()
						.hashCode());
		result = 37
				* result
				+ (getFlagRev101() == null ? 0 : this.getFlagRev101()
						.hashCode());
		result = 37
				* result
				+ (getNumeDlbPres() == null ? 0 : this.getNumeDlbPres()
						.hashCode());
		result = 37
				* result
				+ (getCodiTipoattoEmer() == null ? 0 : this
						.getCodiTipoattoEmer().hashCode());
		result = 37
				* result
				+ (getDataEsclDmc() == null ? 0 : this.getDataEsclDmc()
						.hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
