package it.almavivaitalia.bilancio.commons.bo;

// Generated 4-ago-2015 17.05.07 by Hibernate Tools 3.4.0.CR1

/**
 * AnagAmminDemBOId generated by hbm2java
 */
public class AnagAmminDemBOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Short fkAnnoEse;
	private Integer numeStp;
	private Integer numeApp;

	public AnagAmminDemBOId() {
	}

	public AnagAmminDemBOId(Short fkAnnoEse, Integer numeStp, Integer numeApp) {
		this.fkAnnoEse = fkAnnoEse;
		this.numeStp = numeStp;
		this.numeApp = numeApp;
	}

	public Short getFkAnnoEse() {
		return this.fkAnnoEse;
	}

	public void setFkAnnoEse(Short fkAnnoEse) {
		this.fkAnnoEse = fkAnnoEse;
	}

	public Integer getNumeStp() {
		return this.numeStp;
	}

	public void setNumeStp(Integer numeStp) {
		this.numeStp = numeStp;
	}

	public Integer getNumeApp() {
		return this.numeApp;
	}

	public void setNumeApp(Integer numeApp) {
		this.numeApp = numeApp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnagAmminDemBOId))
			return false;
		AnagAmminDemBOId castOther = (AnagAmminDemBOId) other;

		return ((this.getFkAnnoEse() == castOther.getFkAnnoEse()) || (this
				.getFkAnnoEse() != null && castOther.getFkAnnoEse() != null && this
				.getFkAnnoEse().equals(castOther.getFkAnnoEse())))
				&& ((this.getNumeStp() == castOther.getNumeStp()) || (this
						.getNumeStp() != null && castOther.getNumeStp() != null && this
						.getNumeStp().equals(castOther.getNumeStp())))
				&& ((this.getNumeApp() == castOther.getNumeApp()) || (this
						.getNumeApp() != null && castOther.getNumeApp() != null && this
						.getNumeApp().equals(castOther.getNumeApp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFkAnnoEse() == null ? 0 : this.getFkAnnoEse().hashCode());
		result = 37 * result
				+ (getNumeStp() == null ? 0 : this.getNumeStp().hashCode());
		result = 37 * result
				+ (getNumeApp() == null ? 0 : this.getNumeApp().hashCode());
		return result;
	}

}
