package it.mef.bilancio.demdec.to;
// Generated 6-mag-2015 14.23.06 by Hibernate Tools 3.4.0.CR1



/**
 * MailTestiBO generated by hbm2java
 */
public class StrumentoTO extends AbstractDemTO implements java.io.Serializable {


	private Long id;
	private Integer annoEse;
	private Integer attNumeTipo;
	private Integer numeNum;
	private String statStatus;
	private String numePatr;
	private String annoLeg;
	private String sigla;
	private String numeLeg;
	private String numeArt;
	private String descSubArt;
	private String numeComma;
	private String descSubComma;
	private String codiPunto;
	private String descSubPunto;


	public Long getId() {
		return id;
	}



	public void setId(Long id) {
		this.id = id;
	}



	public Integer getAnnoEse() {
		return annoEse;
	}



	public void setAnnoEse(Integer annoEse) {
		this.annoEse = annoEse;
	}



	public Integer getAttNumeTipo() {
		return attNumeTipo;
	}



	public void setAttNumeTipo(Integer attNumeTipo) {
		this.attNumeTipo = attNumeTipo;
	}



	public Integer getNumeNum() {
		return numeNum;
	}



	public void setNumeNum(Integer numeNum) {
		this.numeNum = numeNum;
	}



	public String getStatStatus() {
		return statStatus;
	}



	public void setStatStatus(String statStatus) {
		this.statStatus = statStatus;
	}



	public String getNumePatr() {
		return numePatr;
	}



	public void setNumePatr(String numePatr) {
		this.numePatr = numePatr;
	}
	
	



	public String getAnnoLeg() {
		return annoLeg;
	}



	public void setAnnoLeg(String annoLeg) {
		this.annoLeg = annoLeg;
	}



	public String getSigla() {
		return sigla;
	}



	public void setSigla(String sigla) {
		this.sigla = sigla;
	}



	public String getNumeLeg() {
		return numeLeg;
	}



	public void setNumeLeg(String numeLeg) {
		this.numeLeg = numeLeg;
	}



	public String getNumeArt() {
		return numeArt;
	}



	public void setNumeArt(String numeArt) {
		this.numeArt = numeArt;
	}



	public String getDescSubArt() {
		return descSubArt;
	}



	public void setDescSubArt(String descSubArt) {
		this.descSubArt = descSubArt;
	}



	public String getNumeComma() {
		return numeComma;
	}



	public void setNumeComma(String numeComma) {
		this.numeComma = numeComma;
	}



	public String getDescSubComma() {
		return descSubComma;
	}



	public void setDescSubComma(String descSubComma) {
		this.descSubComma = descSubComma;
	}



	public String getCodiPunto() {
		return codiPunto;
	}



	public void setCodiPunto(String codiPunto) {
		this.codiPunto = codiPunto;
	}



	public String getDescSubPunto() {
		return descSubPunto;
	}



	public void setDescSubPunto(String descSubPunto) {
		this.descSubPunto = descSubPunto;
	}





	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files





	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((annoEse == null) ? 0 : annoEse.hashCode());
		result = prime * result
				+ ((attNumeTipo == null) ? 0 : attNumeTipo.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((numeNum == null) ? 0 : numeNum.hashCode());
		result = prime * result
				+ ((numePatr == null) ? 0 : numePatr.hashCode());
		result = prime * result
				+ ((statStatus == null) ? 0 : statStatus.hashCode());
		
		result = prime * result + ((annoLeg == null) ? 0 : annoLeg.hashCode());
		result = prime * result + ((sigla == null) ? 0 : sigla.hashCode());
		result = prime * result + ((numeLeg == null) ? 0 : numeLeg.hashCode());
		result = prime * result + ((numeArt == null) ? 0 : numeArt.hashCode());
		result = prime * result + ((descSubArt == null) ? 0 : descSubArt.hashCode());
		result = prime * result + ((numeComma == null) ? 0 : numeComma.hashCode());
		result = prime * result + ((descSubComma == null) ? 0 : descSubComma.hashCode());
		result = prime * result + ((codiPunto == null) ? 0 : codiPunto.hashCode());
		result = prime * result + ((descSubPunto == null) ? 0 : descSubPunto.hashCode());
		
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		StrumentoTO other = (StrumentoTO) obj;
		if (annoEse == null) {
			if (other.annoEse != null)
				return false;
		} else if (!annoEse.equals(other.annoEse))
			return false;
		if (attNumeTipo == null) {
			if (other.attNumeTipo != null)
				return false;
		} else if (!attNumeTipo.equals(other.attNumeTipo))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (numeNum == null) {
			if (other.numeNum != null)
				return false;
		} else if (!numeNum.equals(other.numeNum))
			return false;
		if (numePatr == null) {
			if (other.numePatr != null)
				return false;
		} else if (!numePatr.equals(other.numePatr))
			return false;
		if (statStatus == null) {
			if (other.statStatus != null)
				return false;
		} else if (!statStatus.equals(other.statStatus))
			return false;
		
		if (annoLeg == null) {
			if (other.annoLeg != null)
				return false;
		} else if (!annoLeg.equals(other.annoLeg))
			return false;
		if (sigla == null) {
			if (other.sigla != null)
				return false;
		} else if (!sigla.equals(other.sigla))
			return false;
		if (numeLeg == null) {
			if (other.numeLeg != null)
				return false;
		} else if (!numeLeg.equals(other.numeLeg))
			return false;
		if (numeArt == null) {
			if (other.numeArt != null)
				return false;
		} else if (!numeArt.equals(other.numeArt))
			return false;
		if (descSubArt == null) {
			if (other.descSubArt != null)
				return false;
		} else if (!descSubArt.equals(other.descSubArt))
			return false;
		if (numeComma == null) {
			if (other.numeComma != null)
				return false;
		} else if (!numeComma.equals(other.numeComma))
			return false;
		if (descSubComma == null) {
			if (other.descSubComma != null)
				return false;
		} else if (!descSubComma.equals(other.descSubComma))
			return false;
		if (codiPunto == null) {
			if (other.codiPunto != null)
				return false;
		} else if (!codiPunto.equals(other.codiPunto))
			return false;
		if (descSubPunto == null) {
			if (other.descSubPunto != null)
				return false;
		} else if (!descSubPunto.equals(other.descSubPunto))
			return false;
		return true;
	}


}


