package it.almavivaitalia.bilancio.commons.bo;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1

/**
 * AnagStatoFascicoloBO generated by hbm2java
 */
public class AnagStatoFascicoloBO extends AbstractCommonBO implements
		java.io.Serializable {

	private String id;
	private String descStato;
	private String codiTipoFascicolo;

	public AnagStatoFascicoloBO() {
	}

	public AnagStatoFascicoloBO(String id, String descStato) {
		this.id = id;
		this.descStato = descStato;
	}

	public AnagStatoFascicoloBO(String id, String descStato,
			String codiTipoFascicolo) {
		this.id = id;
		this.descStato = descStato;
		this.codiTipoFascicolo = codiTipoFascicolo;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDescStato() {
		return this.descStato;
	}

	public void setDescStato(String descStato) {
		this.descStato = descStato;
	}

	public String getCodiTipoFascicolo() {
		return this.codiTipoFascicolo;
	}

	public void setCodiTipoFascicolo(String codiTipoFascicolo) {
		this.codiTipoFascicolo = codiTipoFascicolo;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("descStato").append("='").append(getDescStato())
				.append("' ");
		buffer.append("codiTipoFascicolo").append("='")
				.append(getCodiTipoFascicolo()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnagStatoFascicoloBO))
			return false;
		AnagStatoFascicoloBO castOther = (AnagStatoFascicoloBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getDescStato() == castOther.getDescStato()) || (this
						.getDescStato() != null
						&& castOther.getDescStato() != null && this
						.getDescStato().equals(castOther.getDescStato())))
				&& ((this.getCodiTipoFascicolo() == castOther
						.getCodiTipoFascicolo()) || (this
						.getCodiTipoFascicolo() != null
						&& castOther.getCodiTipoFascicolo() != null && this
						.getCodiTipoFascicolo().equals(
								castOther.getCodiTipoFascicolo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getDescStato() == null ? 0 : this.getDescStato().hashCode());
		result = 37
				* result
				+ (getCodiTipoFascicolo() == null ? 0 : this
						.getCodiTipoFascicolo().hashCode());
		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
