package it.mef.bilancio.demdec.to;

// Generated 7-set-2010 11.52.15 by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.util.Date;

/**
 * ApplicationTO generated by hbm2java
 */
public class CronologicoTransExcelTO extends AbstractDemTO implements Serializable  {//INIZIO METODO
	private static final long serialVersionUID = 1L;
	
	private Integer codiId;
    private String  codiNome;
    private String  descDescr;
    private Date    dataOpraz;
    private String  orarOperaz;
    private String  dataOprazFormatted;
    private String  orarOperazFormatted;
    private String  descUtente;
    private String  codiUtente;
    private String  descDescrTrans;
    private String  ordVisu;
    private String  campo;
    private String  textOldVal;
    private String  textNewVal;
    private String  modificato;
    
	public Integer getCodiId() {//INIZIO METODO
		return codiId;
	}//FINE METODO
	public void setCodiId(Integer codiId) {//INIZIO METODO
		this.codiId = codiId;
	}//FINE METODO
	public String getCodiNome() {//INIZIO METODO
		return codiNome;
	}//FINE METODO
	public void setCodiNome(String codiNome) {//INIZIO METODO
		this.codiNome = codiNome;
	}//FINE METODO
	public String getDescDescr() {//INIZIO METODO
		return descDescr;
	}//FINE METODO
	public void setDescDescr(String descDescr) {//INIZIO METODO
		this.descDescr = descDescr;
	}//FINE METODO
	public Date getDataOpraz() {//INIZIO METODO
		return dataOpraz;
	}//FINE METODO
	public void setDataOpraz(Date dataOpraz) {//INIZIO METODO
		this.dataOpraz = dataOpraz;
	}//FINE METODO
	public String getOrarOperaz() {//INIZIO METODO
		return orarOperaz;
	}//FINE METODO
	public void setOrarOperaz(String orarOperaz) {//INIZIO METODO
		this.orarOperaz = orarOperaz;
	}//FINE METODO
	public String getDescUtente() {//INIZIO METODO
		return descUtente;
	}//FINE METODO
	public void setDescUtente(String descUtente) {//INIZIO METODO
		this.descUtente = descUtente;
	}//FINE METODO
	public String getCodiUtente() {//INIZIO METODO
		return codiUtente;
	}//FINE METODO
	public void setCodiUtente(String codiUtente) {//INIZIO METODO
		this.codiUtente = codiUtente;
	}//FINE METODO
	public String getDescDescrTrans() {//INIZIO METODO
		return descDescrTrans;
	}//FINE METODO
	public void setDescDescrTrans(String descDescrTrans) {//INIZIO METODO
		this.descDescrTrans = descDescrTrans;
	}//FINE METODO
	public String getDataOprazFormatted() {//INIZIO METODO
		return dataOprazFormatted;
	}//FINE METODO
	public void setDataOprazFormatted(String dataOprazFormatted) {//INIZIO METODO
		this.dataOprazFormatted = dataOprazFormatted;
	}//FINE METODO
	public String getOrarOperazFormatted() {//INIZIO METODO
		return orarOperazFormatted;
	}//FINE METODO
	public void setOrarOperazFormatted(String orarOperazFormatted) {//INIZIO METODO
		this.orarOperazFormatted = orarOperazFormatted;
	}//FINE METODO
	public String getOrdVisu() {//INIZIO METODO
		return ordVisu;
	}//FINE METODO
	public void setOrdVisu(String ordVisu) {//INIZIO METODO
		this.ordVisu = ordVisu;
	}//FINE METODO
	public String getCampo() {//INIZIO METODO
		return campo;
	}//FINE METODO
	public void setCampo(String campo) {//INIZIO METODO
		this.campo = campo;
	}//FINE METODO
	public String getTextOldVal() {//INIZIO METODO
		return textOldVal;
	}//FINE METODO
	public void setTextOldVal(String textOldVal) {//INIZIO METODO
		this.textOldVal = textOldVal;
	}//FINE METODO
	public String getTextNewVal() {//INIZIO METODO
		return textNewVal;
	}//FINE METODO
	public void setTextNewVal(String textNewVal) {//INIZIO METODO
		this.textNewVal = textNewVal;
	}//FINE METODO
	public String getModificato() {//INIZIO METODO
		return modificato;
	}//FINE METODO
	public void setModificato(String modificato) {//INIZIO METODO
		this.modificato = modificato;
	}//FINE METODO
	public static long getSerialversionuid() {//INIZIO METODO
		return serialVersionUID;
	}//FINE METODO
	
    
    
}//FINE METODO
