package it.almavivaitalia.bilancio.commons.bo;

import java.util.Date;

// Generated 22-lug-2015 15.41.08 by Hibernate Tools 3.4.0.CR1

/**
 * SospesiRedBO generated by hbm2java
 */
public class SospesiRedBO extends AbstractCommonBO implements
		java.io.Serializable {

	private String id;
	private String codiIdRed;
	private String codiOperazione;
	private String statEsito;
	private String codiAooProtocollo;
	private String numeProtocollo;
	private String descTipoProtocollo;
	private Date dataProtocollo;

	public SospesiRedBO() {
	}

	public SospesiRedBO(String id, String codiIdRed) {
		this.id = id;
		this.codiIdRed = codiIdRed;
	}

	public SospesiRedBO(String id, String codiIdRed,
			String codiOperazione, String statEsito) {
		this.id = id;
		this.codiIdRed = codiIdRed;
		this.codiOperazione = codiOperazione;
		this.statEsito = statEsito;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCodiIdRed() {
		return this.codiIdRed;
	}

	public void setCodiIdRed(String codiIdRed) {
		this.codiIdRed = codiIdRed;
	}

	public String getCodiOperazione() {
		return this.codiOperazione;
	}

	public void setCodiOperazione(String codiOperazione) {
		this.codiOperazione = codiOperazione;
	}

	public String getStatEsito() {
		return this.statEsito;
	}

	public void setStatEsito(String statEsito) {
		this.statEsito = statEsito;
	}

	public String getCodiAooProtocollo() {
		return codiAooProtocollo;
	}

	public void setCodiAooProtocollo(String codiAooProtocollo) {
		this.codiAooProtocollo = codiAooProtocollo;
	}

	public String getNumeProtocollo() {
		return numeProtocollo;
	}

	public void setNumeProtocollo(String numeProtocollo) {
		this.numeProtocollo = numeProtocollo;
	}

	public String getDescTipoProtocollo() {
		return descTipoProtocollo;
	}

	public void setDescTipoProtocollo(String descTipoProtocollo) {
		this.descTipoProtocollo = descTipoProtocollo;
	}

	public Date getDataProtocollo() {
		return dataProtocollo;
	}

	public void setDataProtocollo(Date dataProtocollo) {
		this.dataProtocollo = dataProtocollo;
	}


	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("numeVersion").append("='").append(getNumeVersion())
				.append("' ");
		buffer.append("codiIdRed").append("='").append(getCodiIdRed())
				.append("' ");
		buffer.append("codiOperazione").append("='")
				.append(getCodiOperazione()).append("' ");
		buffer.append("statEsito").append("='").append(getStatEsito())
				.append("' ");
		buffer.append("codiAooProtocollo").append("='").append(getCodiAooProtocollo())
				.append("' ");
		buffer.append("numeProtocollo").append("='").append(getNumeProtocollo())
				.append("' ");
		buffer.append("descTipoProtocollo").append("='").append(getDescTipoProtocollo())
				.append("' ");
		buffer.append("dataProtocollo").append("='").append(getDataProtocollo().toString())
			.append("' ");
		buffer.append("]");

		return buffer.toString();

	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((codiAooProtocollo == null) ? 0 : codiAooProtocollo
						.hashCode());
		result = prime * result
				+ ((codiIdRed == null) ? 0 : codiIdRed.hashCode());
		result = prime * result
				+ ((codiOperazione == null) ? 0 : codiOperazione.hashCode());
		result = prime * result
				+ ((dataProtocollo == null) ? 0 : dataProtocollo.hashCode());
		result = prime
				* result
				+ ((descTipoProtocollo == null) ? 0 : descTipoProtocollo
						.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((numeProtocollo == null) ? 0 : numeProtocollo.hashCode());
		result = prime * result
				+ ((statEsito == null) ? 0 : statEsito.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SospesiRedBO other = (SospesiRedBO) obj;
		if (codiAooProtocollo == null) {
			if (other.codiAooProtocollo != null)
				return false;
		} else if (!codiAooProtocollo.equals(other.codiAooProtocollo))
			return false;
		if (codiIdRed == null) {
			if (other.codiIdRed != null)
				return false;
		} else if (!codiIdRed.equals(other.codiIdRed))
			return false;
		if (codiOperazione == null) {
			if (other.codiOperazione != null)
				return false;
		} else if (!codiOperazione.equals(other.codiOperazione))
			return false;
		if (dataProtocollo == null) {
			if (other.dataProtocollo != null)
				return false;
		} else if (!dataProtocollo.equals(other.dataProtocollo))
			return false;
		if (descTipoProtocollo == null) {
			if (other.descTipoProtocollo != null)
				return false;
		} else if (!descTipoProtocollo.equals(other.descTipoProtocollo))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (numeProtocollo == null) {
			if (other.numeProtocollo != null)
				return false;
		} else if (!numeProtocollo.equals(other.numeProtocollo))
			return false;
		if (statEsito == null) {
			if (other.statEsito != null)
				return false;
		} else if (!statEsito.equals(other.statEsito))
			return false;
		return true;
	}


	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
