package it.almavivaitalia.bilancio.commons.bo;

// Generated 21-set-2015 11.14.12 by Hibernate Tools 3.4.0.CR1

/**
 * SottoFascicoliRedBOId generated by hbm2java
 */
public class SottoFascicoliRedBOId implements java.io.Serializable {

	private String codiIdRed;
	private Long fkNumeIdFascicolo;

	public SottoFascicoliRedBOId() {
	}

	public SottoFascicoliRedBOId(String codiIdRed, Long fkNumeIdFascicolo) {
		this.codiIdRed = codiIdRed;
		this.fkNumeIdFascicolo = fkNumeIdFascicolo;
	}

	public String getCodiIdRed() {
		return this.codiIdRed;
	}

	public void setCodiIdRed(String codiIdRed) {
		this.codiIdRed = codiIdRed;
	}

	public Long getFkNumeIdFascicolo() {
		return this.fkNumeIdFascicolo;
	}

	public void setFkNumeIdFascicolo(Long fkNumeIdFascicolo) {
		this.fkNumeIdFascicolo = fkNumeIdFascicolo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SottoFascicoliRedBOId))
			return false;
		SottoFascicoliRedBOId castOther = (SottoFascicoliRedBOId) other;

		return ((this.getCodiIdRed() == castOther.getCodiIdRed()) || (this
				.getCodiIdRed() != null && castOther.getCodiIdRed() != null && this
				.getCodiIdRed().equals(castOther.getCodiIdRed())))
				&& ((this.getFkNumeIdFascicolo() == castOther
						.getFkNumeIdFascicolo()) || (this
						.getFkNumeIdFascicolo() != null
						&& castOther.getFkNumeIdFascicolo() != null && this
						.getFkNumeIdFascicolo().equals(
								castOther.getFkNumeIdFascicolo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodiIdRed() == null ? 0 : this.getCodiIdRed().hashCode());
		result = 37
				* result
				+ (getFkNumeIdFascicolo() == null ? 0 : this
						.getFkNumeIdFascicolo().hashCode());
		return result;
	}

}
