package it.mef.bilancio.demdec.to;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * TipoDocumentoBO generated by hbm2java
 */
public class TipoDocumentoTO extends AbstractDemTO implements
		java.io.Serializable {

	private String id;
	private String descDescrizioneDoc;
	private List<DocumentiTO> documentiList = new ArrayList<DocumentiTO>(0);

	public TipoDocumentoTO() {
	}

	public TipoDocumentoTO(String id) {
		this.id = id;
	}

	public TipoDocumentoTO(String id, String descDescrizioneDoc,
			List<DocumentiTO> documentiList) {
		this.id = id;
		this.descDescrizioneDoc = descDescrizioneDoc;
		this.documentiList = documentiList;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDescDescrizioneDoc() {
		return this.descDescrizioneDoc;
	}

	public void setDescDescrizioneDoc(String descDescrizioneDoc) {
		this.descDescrizioneDoc = descDescrizioneDoc;
	}

	public List<DocumentiTO> getDocumentiList() {
		return this.documentiList;
	}

	public void setDocumentiList(List<DocumentiTO> documentiList) {
		this.documentiList = documentiList;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("descDescrizioneDoc").append("='")
				.append(getDescDescrizioneDoc()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoDocumentoTO))
			return false;
		TipoDocumentoTO castOther = (TipoDocumentoTO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getDescDescrizioneDoc() == castOther
						.getDescDescrizioneDoc()) || (this
						.getDescDescrizioneDoc() != null
						&& castOther.getDescDescrizioneDoc() != null && this
						.getDescDescrizioneDoc().equals(
								castOther.getDescDescrizioneDoc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getDescDescrizioneDoc() == null ? 0 : this
						.getDescDescrizioneDoc().hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
