package it.almavivaitalia.bilancio.commons.bo;

// Generated 22-lug-2015 15.41.08 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * MailTestiBO generated by hbm2java
 */
public class MailTestiBO extends AbstractCommonBO implements
		java.io.Serializable {

	private BigDecimal id;
	private String codiFunzione;
	private String textIndEmailA;
	private String textIndEmailCc;
	private String textOggettoEmail;
	private String textEmail;
	private String flagInvioSn;
	private String flagPecSn;

	public MailTestiBO() {
	}

	public MailTestiBO(BigDecimal id,  String codiFunzione,
			String textOggettoEmail, String textEmail) {
		this.id = id;
		this.codiFunzione = codiFunzione;
		this.textOggettoEmail = textOggettoEmail;
		this.textEmail = textEmail;
	}

	public MailTestiBO(BigDecimal id, String codiFunzione,
			String textIndEmailA, String textIndEmailCc,
			String textOggettoEmail, String textEmail, String flagInvioSn,
			String flagPecSn) {
		this.id = id;
		this.codiFunzione = codiFunzione;
		this.textIndEmailA = textIndEmailA;
		this.textIndEmailCc = textIndEmailCc;
		this.textOggettoEmail = textOggettoEmail;
		this.textEmail = textEmail;
		this.flagInvioSn = flagInvioSn;
		this.flagPecSn = flagPecSn;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getCodiFunzione() {
		return this.codiFunzione;
	}

	public void setCodiFunzione(String codiFunzione) {
		this.codiFunzione = codiFunzione;
	}

	public String getTextIndEmailA() {
		return this.textIndEmailA;
	}

	public void setTextIndEmailA(String textIndEmailA) {
		this.textIndEmailA = textIndEmailA;
	}

	public String getTextIndEmailCc() {
		return this.textIndEmailCc;
	}

	public void setTextIndEmailCc(String textIndEmailCc) {
		this.textIndEmailCc = textIndEmailCc;
	}

	public String getTextOggettoEmail() {
		return this.textOggettoEmail;
	}

	public void setTextOggettoEmail(String textOggettoEmail) {
		this.textOggettoEmail = textOggettoEmail;
	}

	public String getTextEmail() {
		return this.textEmail;
	}

	public void setTextEmail(String textEmail) {
		this.textEmail = textEmail;
	}

	public String getFlagInvioSn() {
		return this.flagInvioSn;
	}

	public void setFlagInvioSn(String flagInvioSn) {
		this.flagInvioSn = flagInvioSn;
	}

	public String getFlagPecSn() {
		return this.flagPecSn;
	}

	public void setFlagPecSn(String flagPecSn) {
		this.flagPecSn = flagPecSn;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("numeVersion").append("='").append(getNumeVersion())
				.append("' ");
		buffer.append("codiFunzione").append("='").append(getCodiFunzione())
				.append("' ");
		buffer.append("textIndEmailA").append("='").append(getTextIndEmailA())
				.append("' ");
		buffer.append("textIndEmailCc").append("='")
				.append(getTextIndEmailCc()).append("' ");
		buffer.append("textOggettoEmail").append("='")
				.append(getTextOggettoEmail()).append("' ");
		buffer.append("textEmail").append("='").append(getTextEmail())
				.append("' ");
		buffer.append("flagInvioSn").append("='").append(getFlagInvioSn())
				.append("' ");
		buffer.append("flagPecSn").append("='").append(getFlagPecSn())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MailTestiBO))
			return false;
		MailTestiBO castOther = (MailTestiBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getNumeVersion() == castOther.getNumeVersion()))
				&& ((this.getCodiFunzione() == castOther.getCodiFunzione()) || (this
						.getCodiFunzione() != null
						&& castOther.getCodiFunzione() != null && this
						.getCodiFunzione().equals(castOther.getCodiFunzione())))
				&& ((this.getTextIndEmailA() == castOther.getTextIndEmailA()) || (this
						.getTextIndEmailA() != null
						&& castOther.getTextIndEmailA() != null && this
						.getTextIndEmailA()
						.equals(castOther.getTextIndEmailA())))
				&& ((this.getTextIndEmailCc() == castOther.getTextIndEmailCc()) || (this
						.getTextIndEmailCc() != null
						&& castOther.getTextIndEmailCc() != null && this
						.getTextIndEmailCc().equals(
								castOther.getTextIndEmailCc())))
				&& ((this.getTextOggettoEmail() == castOther
						.getTextOggettoEmail()) || (this.getTextOggettoEmail() != null
						&& castOther.getTextOggettoEmail() != null && this
						.getTextOggettoEmail().equals(
								castOther.getTextOggettoEmail())))
				&& ((this.getTextEmail() == castOther.getTextEmail()) || (this
						.getTextEmail() != null
						&& castOther.getTextEmail() != null && this
						.getTextEmail().equals(castOther.getTextEmail())))
				&& ((this.getFlagInvioSn() == castOther.getFlagInvioSn()) || (this
						.getFlagInvioSn() != null
						&& castOther.getFlagInvioSn() != null && this
						.getFlagInvioSn().equals(castOther.getFlagInvioSn())))
				&& ((this.getFlagPecSn() == castOther.getFlagPecSn()) || (this
						.getFlagPecSn() != null
						&& castOther.getFlagPecSn() != null && this
						.getFlagPecSn().equals(castOther.getFlagPecSn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getNumeVersion());
		result = 37
				* result
				+ (getCodiFunzione() == null ? 0 : this.getCodiFunzione()
						.hashCode());
		result = 37
				* result
				+ (getTextIndEmailA() == null ? 0 : this.getTextIndEmailA()
						.hashCode());
		result = 37
				* result
				+ (getTextIndEmailCc() == null ? 0 : this.getTextIndEmailCc()
						.hashCode());
		result = 37
				* result
				+ (getTextOggettoEmail() == null ? 0 : this
						.getTextOggettoEmail().hashCode());
		result = 37 * result
				+ (getTextEmail() == null ? 0 : this.getTextEmail().hashCode());
		result = 37
				* result
				+ (getFlagInvioSn() == null ? 0 : this.getFlagInvioSn()
						.hashCode());
		result = 37 * result
				+ (getFlagPecSn() == null ? 0 : this.getFlagPecSn().hashCode());
		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
