package it.mef.bilancio.demdec.to;

import it.almavivaitalia.bilancio.commons.to.AbstractCommonTO;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1


/**
 * AnagModelliIterBO generated by hbm2java
 */
public class AnagModelliIterTO extends AbstractCommonTO implements
		java.io.Serializable {

	private Short id;
	private String descIter;

	public AnagModelliIterTO() {
	}

	public AnagModelliIterTO(Short id) {
		this.id = id;
	}

	public AnagModelliIterTO(Short id, String descIter) {
		this.id = id;
		this.descIter = descIter;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public String getDescIter() {
		return this.descIter;
	}

	public void setDescIter(String descIter) {
		this.descIter = descIter;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("numeVersion").append("='").append(getNumeVersion())
				.append("' ");
		buffer.append("descIter").append("='").append(getDescIter())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnagModelliIterTO))
			return false;
		AnagModelliIterTO castOther = (AnagModelliIterTO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getDescIter() == castOther.getDescIter()) || (this
						.getDescIter() != null
						&& castOther.getDescIter() != null && this
						.getDescIter().equals(castOther.getDescIter())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getDescIter() == null ? 0 : this.getDescIter().hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
