package it.almavivaitalia.bilancio.commons.bo;
// Generated 27-ago-2015 11.40.14 by Hibernate Tools 3.4.0.CR1



/**
 * AnagAmminUfficiBO generated by hbm2java
 */
public class AnagAmminUfficiBO extends AbstractCommonBO implements java.io.Serializable {


     private AnagAmminUfficiBOId id;

    public AnagAmminUfficiBO() {
    }

    public AnagAmminUfficiBO(AnagAmminUfficiBOId id) {
       this.id = id;
    }
   
    public AnagAmminUfficiBOId getId() {
        return this.id;
    }
    
    public void setId(AnagAmminUfficiBOId id) {
        this.id = id;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AnagAmminUfficiBO) ) return false;
		 AnagAmminUfficiBO castOther = ( AnagAmminUfficiBO ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         return result;
   }   

  // The following is extra code specified in the hbm.xml files
private static final long serialVersionUID = 1L;
  // end of extra code specified in the hbm.xml files

}


