package it.mef.bilancio.demdec.web.services.type;


// Generated 5-giu-2015 12.17.04 by Hibernate Tools 3.4.0.CR1


/**
 * AnagAmminDemBO generated by hbm2java
 */
public class AnagAmminDemType implements java.io.Serializable {

	private Short fkAnnoEse;
	private Integer numeStp;
	private Integer numeApp;
	private String  descAmm;

	public AnagAmminDemType() {
	}



	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

	public Short getFkAnnoEse() {
		return fkAnnoEse;
	}



	public void setFkAnnoEse(Short fkAnnoEse) {
		this.fkAnnoEse = fkAnnoEse;
	}



	public Integer getNumeStp() {
		return numeStp;
	}



	public void setNumeStp(Integer numeStp) {
		this.numeStp = numeStp;
	}



	public Integer getNumeApp() {
		return numeApp;
	}



	public void setNumeApp(Integer numeApp) {
		this.numeApp = numeApp;
	}



	public String getDescAmm() {
		return descAmm;
	}



	public void setDescAmm(String descAmm) {
		this.descAmm = descAmm;
	}

}
