package it.almavivaitalia.bilancio.commons.bo;

// Generated 5-giu-2015 12.17.04 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * ItemBO generated by hbm2java
 */
public class ItemBO extends AbstractCommonBO implements java.io.Serializable {

	private Long id;
	private ActionBO action;
	private ItemBO item;
	private MenuBO menu;
	private String codiItem;
	private Integer numeSequence;
	private String descItem;
	private String descItemEstesa;
	private List<MenuBO> menuList = new ArrayList<MenuBO>(0);
	private List<ItemBO> itemList = new ArrayList<ItemBO>(0);

	public ItemBO() {
	}

	public ItemBO(ActionBO action, ItemBO item, MenuBO menu, String codiItem,
			Integer numeSequence, String descItem, List<MenuBO> menuList, List<ItemBO> itemList) {
		this.action = action;
		this.item = item;
		this.menu = menu;
		this.codiItem = codiItem;
		this.numeSequence = numeSequence;
		this.descItem = descItem;
		this.menuList = menuList;
		this.itemList = itemList;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public ActionBO getAction() {
		return this.action;
	}

	public void setAction(ActionBO action) {
		this.action = action;
	}

	public ItemBO getItem() {
		return this.item;
	}

	public void setItem(ItemBO item) {
		this.item = item;
	}

	public MenuBO getMenu() {
		return this.menu;
	}

	public void setMenu(MenuBO menu) {
		this.menu = menu;
	}

	public String getCodiItem() {
		return this.codiItem;
	}

	public void setCodiItem(String codiItem) {
		this.codiItem = codiItem;
	}

	public Integer getNumeSequence() {
		return this.numeSequence;
	}

	public void setNumeSequence(Integer numeSequence) {
		this.numeSequence = numeSequence;
	}

	public String getDescItem() {
		return this.descItem;
	}

	public void setDescItem(String descItem) {
		this.descItem = descItem;
	}
	
	public String getDescItemEstesa() {
		return descItemEstesa;
	}

	public void setDescItemEstesa(String descItemEstesa) {
		this.descItemEstesa = descItemEstesa;
	}

	public List<MenuBO> getMenuList() {
		return this.menuList;
	}

	public void setMenuList(List<MenuBO> menuList) {
		this.menuList = menuList;
	}

	public List<ItemBO> getItemList() {
		return this.itemList;
	}

	public void setItemList(List<ItemBO> itemList) {
		this.itemList = itemList;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("action").append("='").append(getAction()).append("' ");
		buffer.append("item").append("='").append(getItem()).append("' ");
		buffer.append("menu").append("='").append(getMenu()).append("' ");
		buffer.append("codiItem").append("='").append(getCodiItem())
				.append("' ");
		buffer.append("numeSequence").append("='").append(getNumeSequence())
				.append("' ");
		buffer.append("descItem").append("='").append(getDescItem())
				.append("' ");
		 buffer.append("descItemEstesa").append("='").append(getDescItemEstesa())
		 		.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemBO))
			return false;
		ItemBO castOther = (ItemBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getAction() == castOther.getAction()) || (this
						.getAction() != null && castOther.getAction() != null && this
						.getAction().equals(castOther.getAction())))
				&& ((this.getItem() == castOther.getItem()) || (this.getItem() != null
						&& castOther.getItem() != null && this.getItem()
						.equals(castOther.getItem())))
				&& ((this.getMenu() == castOther.getMenu()) || (this.getMenu() != null
						&& castOther.getMenu() != null && this.getMenu()
						.equals(castOther.getMenu())))
				&& ((this.getCodiItem() == castOther.getCodiItem()) || (this
						.getCodiItem() != null
						&& castOther.getCodiItem() != null && this
						.getCodiItem().equals(castOther.getCodiItem())))
				&& ((this.getNumeSequence() == castOther.getNumeSequence()) || (this
						.getNumeSequence() != null
						&& castOther.getNumeSequence() != null && this
						.getNumeSequence().equals(castOther.getNumeSequence())))
				&& ((this.getDescItem() == castOther.getDescItem()) || (this
						.getDescItem() != null
						&& castOther.getDescItem() != null && this
						.getDescItem().equals(castOther.getDescItem())))
				&& ((this.getDescItemEstesa() == castOther.getDescItemEstesa()) || ( this
						.getDescItemEstesa() !=null && castOther.getDescItemEstesa()!=null 
						&& this.getDescItemEstesa().equals(castOther.getDescItemEstesa())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result
				+ (getItem() == null ? 0 : this.getItem().hashCode());
		result = 37 * result
				+ (getMenu() == null ? 0 : this.getMenu().hashCode());
		result = 37 * result
				+ (getCodiItem() == null ? 0 : this.getCodiItem().hashCode());
		result = 37
				* result
				+ (getNumeSequence() == null ? 0 : this.getNumeSequence()
						.hashCode());
		result = 37 * result
				+ (getDescItem() == null ? 0 : this.getDescItem().hashCode());
		result = 37 
				* result 
				+ (getDescItemEstesa() == null ? 0 : this.getDescItemEstesa().hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
