package it.almavivaitalia.bilancio.commons.bo;

// Generated 5-giu-2015 12.17.04 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * MenuBO generated by hbm2java
 */
public class MenuBO extends AbstractCommonBO implements java.io.Serializable {

	private Long id;
	private String codiMenu;
	private String descCodiMenu;
	private List<ItemBO> itemList = new ArrayList<ItemBO>(0);
	private List<ProfiloBO> profiloList = new ArrayList<ProfiloBO>(0);
	private List<ItemBO> itemList_1 = new ArrayList<ItemBO>(0);

	public MenuBO() {
	}

	public MenuBO(String codiMenu) {
		this.codiMenu = codiMenu;
	}

	public MenuBO(String codiMenu, String descCodiMenu, List<ItemBO> itemList,
			List<ProfiloBO> profiloList, List<ItemBO> itemList_1) {
		this.codiMenu = codiMenu;
		this.descCodiMenu = descCodiMenu;
		this.itemList = itemList;
		this.profiloList = profiloList;
		this.itemList_1 = itemList_1;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCodiMenu() {
		return this.codiMenu;
	}

	public void setCodiMenu(String codiMenu) {
		this.codiMenu = codiMenu;
	}

	public String getDescCodiMenu() {
		return this.descCodiMenu;
	}

	public void setDescCodiMenu(String descCodiMenu) {
		this.descCodiMenu = descCodiMenu;
	}

	public List<ItemBO> getItemList() {
		return this.itemList;
	}

	public void setItemList(List<ItemBO> itemList) {
		this.itemList = itemList;
	}

	public List<ProfiloBO> getProfiloList() {
		return this.profiloList;
	}

	public void setProfiloList(List<ProfiloBO> profiloList) {
		this.profiloList = profiloList;
	}

	public List<ItemBO> getItemList_1() {
		return this.itemList_1;
	}

	public void setItemList_1(List<ItemBO> itemList_1) {
		this.itemList_1 = itemList_1;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("codiMenu").append("='").append(getCodiMenu())
				.append("' ");
		buffer.append("descCodiMenu").append("='").append(getDescCodiMenu())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MenuBO))
			return false;
		MenuBO castOther = (MenuBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getCodiMenu() == castOther.getCodiMenu()) || (this
						.getCodiMenu() != null
						&& castOther.getCodiMenu() != null && this
						.getCodiMenu().equals(castOther.getCodiMenu())))
				&& ((this.getDescCodiMenu() == castOther.getDescCodiMenu()) || (this
						.getDescCodiMenu() != null
						&& castOther.getDescCodiMenu() != null && this
						.getDescCodiMenu().equals(castOther.getDescCodiMenu())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCodiMenu() == null ? 0 : this.getCodiMenu().hashCode());
		result = 37
				* result
				+ (getDescCodiMenu() == null ? 0 : this.getDescCodiMenu()
						.hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
