package it.almavivaitalia.bilancio.commons.bo;

// Generated 23-lug-2015 10.39.39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DocumentiRedBO generated by hbm2java
 */
public class DocumentiRedBO extends AbstractCommonBO implements
		java.io.Serializable {

	private DocumentiRedBOId id;
	private AnagAmminDemBO anagAmminDem;
	private AnagRagionerieDemBO anagRagionerieDem;
	private TipoDocumentoBO tipoDocumento;
	private SottoFascicoliRedBO sottoFascicoliRed;
	private String codiIdRed;
	private String codiGuidDocumentoTrasf;
	private String codiGuidDocProv;
	private String codiGuidDocOrigProv;
	private String descTipoFlusso;
	private Integer statDocumento;
	private String descStatoDocumento;
	private String codiProtocollo;
	private Integer flagVisibilitaCdc01;
	private Date dataDocumento;
	private Date dataArrivo;
	private Date dataChiusura;
	private Date dataAggiornamento;
	private Date dataAnnullamento;
	private String descFilename;
	private String codiMimeTypeOrig;
	private String codiHash;
	private DescDocumentoBO descDocumento;
	private Integer numeRag;

	public DocumentiRedBO() {
	}

	public DocumentiRedBO(DocumentiRedBOId id, TipoDocumentoBO tipoDocumento,
			SottoFascicoliRedBO sottoFascicoliRed, String codiGuidDocProv,
			Integer statDocumento, Integer flagVisibilitaCdc01) {
		this.id = id;
		this.tipoDocumento = tipoDocumento;
		this.sottoFascicoliRed = sottoFascicoliRed;
		this.codiGuidDocProv = codiGuidDocProv;
		this.statDocumento = statDocumento;
		this.flagVisibilitaCdc01 = flagVisibilitaCdc01;
	}

	public DocumentiRedBO(DocumentiRedBOId id, AnagAmminDemBO anagAmminDem,
			AnagRagionerieDemBO anagRagionerieDem,
			TipoDocumentoBO tipoDocumento,
			SottoFascicoliRedBO sottoFascicoliRed,
			String codiGuidDocumentoTrasf, String codiGuidDocProv,
			String codiGuidDocOrigProv, String descTipoFlusso,
			Integer statDocumento, String codiProtocollo,
			Integer flagVisibilitaCdc01, Date dataDocumento, Date dataArrivo,
			Date dataChiusura, Date dataAggiornamento, Date dataAnnullamento,
			String descFilename, String codiMimeTypeOrig, String codiHash) {
		this.id = id;
		this.anagAmminDem = anagAmminDem;
		this.anagRagionerieDem = anagRagionerieDem;
		this.tipoDocumento = tipoDocumento;
		this.sottoFascicoliRed = sottoFascicoliRed;
		this.codiGuidDocumentoTrasf = codiGuidDocumentoTrasf;
		this.codiGuidDocProv = codiGuidDocProv;
		this.codiGuidDocOrigProv = codiGuidDocOrigProv;
		this.descTipoFlusso = descTipoFlusso;
		this.statDocumento = statDocumento;
		this.codiProtocollo = codiProtocollo;
		this.flagVisibilitaCdc01 = flagVisibilitaCdc01;
		this.dataDocumento = dataDocumento;
		this.dataArrivo = dataArrivo;
		this.dataChiusura = dataChiusura;
		this.dataAggiornamento = dataAggiornamento;
		this.dataAnnullamento = dataAnnullamento;
		this.descFilename = descFilename;
		this.codiMimeTypeOrig = codiMimeTypeOrig;
		this.codiHash = codiHash;
	}

	public DocumentiRedBOId getId() {
		return this.id;
	}

	public void setId(DocumentiRedBOId id) {
		this.id = id;
	}

	public AnagAmminDemBO getAnagAmminDem() {
		return this.anagAmminDem;
	}

	public void setAnagAmminDem(AnagAmminDemBO anagAmminDem) {
		this.anagAmminDem = anagAmminDem;
	}

	public AnagRagionerieDemBO getAnagRagionerieDem() {
		return this.anagRagionerieDem;
	}

	public void setAnagRagionerieDem(AnagRagionerieDemBO anagRagionerieDem) {
		this.anagRagionerieDem = anagRagionerieDem;
	}

	public TipoDocumentoBO getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumentoBO tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public SottoFascicoliRedBO getSottoFascicoliRed() {
		return this.sottoFascicoliRed;
	}

	public void setSottoFascicoliRed(SottoFascicoliRedBO sottoFascicoliRed) {
		this.sottoFascicoliRed = sottoFascicoliRed;
	}

	public String getCodiIdRed() {
		return codiIdRed;
	}

	public void setCodiIdRed(String codiIdRed) {
		this.codiIdRed = codiIdRed;
	}

	public String getCodiGuidDocumentoTrasf() {
		return this.codiGuidDocumentoTrasf;
	}

	public void setCodiGuidDocumentoTrasf(String codiGuidDocumentoTrasf) {
		this.codiGuidDocumentoTrasf = codiGuidDocumentoTrasf;
	}

	public String getCodiGuidDocProv() {
		return this.codiGuidDocProv;
	}

	public void setCodiGuidDocProv(String codiGuidDocProv) {
		this.codiGuidDocProv = codiGuidDocProv;
	}

	public String getCodiGuidDocOrigProv() {
		return this.codiGuidDocOrigProv;
	}

	public void setCodiGuidDocOrigProv(String codiGuidDocOrigProv) {
		this.codiGuidDocOrigProv = codiGuidDocOrigProv;
	}

	public String getDescTipoFlusso() {
		return this.descTipoFlusso;
	}

	public void setDescTipoFlusso(String descTipoFlusso) {
		this.descTipoFlusso = descTipoFlusso;
	}

	public Integer getStatDocumento() {
		return this.statDocumento;
	}

	public void setStatDocumento(Integer statDocumento) {
		this.statDocumento = statDocumento;
	}

	public String getDescStatoDocumento() {
		return descStatoDocumento;
	}

	public void setDescStatoDocumento(String descStatoDocumento) {
		this.descStatoDocumento = descStatoDocumento;
	}

	public String getCodiProtocollo() {
		return this.codiProtocollo;
	}

	public void setCodiProtocollo(String codiProtocollo) {
		this.codiProtocollo = codiProtocollo;
	}

	public Integer getFlagVisibilitaCdc01() {
		return this.flagVisibilitaCdc01;
	}

	public void setFlagVisibilitaCdc01(Integer flagVisibilitaCdc01) {
		this.flagVisibilitaCdc01 = flagVisibilitaCdc01;
	}

	public Date getDataDocumento() {
		return this.dataDocumento;
	}

	public void setDataDocumento(Date dataDocumento) {
		this.dataDocumento = dataDocumento;
	}

	public Date getDataArrivo() {
		return this.dataArrivo;
	}

	public void setDataArrivo(Date dataArrivo) {
		this.dataArrivo = dataArrivo;
	}

	public Date getDataChiusura() {
		return this.dataChiusura;
	}

	public void setDataChiusura(Date dataChiusura) {
		this.dataChiusura = dataChiusura;
	}

	public Date getDataAggiornamento() {
		return this.dataAggiornamento;
	}

	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	public Date getDataAnnullamento() {
		return this.dataAnnullamento;
	}

	public void setDataAnnullamento(Date dataAnnullamento) {
		this.dataAnnullamento = dataAnnullamento;
	}

	public String getDescFilename() {
		return this.descFilename;
	}

	public void setDescFilename(String descFilename) {
		this.descFilename = descFilename;
	}

	public String getCodiMimeTypeOrig() {
		return this.codiMimeTypeOrig;
	}

	public void setCodiMimeTypeOrig(String codiMimeTypeOrig) {
		this.codiMimeTypeOrig = codiMimeTypeOrig;
	}

	public String getCodiHash() {
		return this.codiHash;
	}

	public void setCodiHash(String codiHash) {
		this.codiHash = codiHash;
	}
	
	public DescDocumentoBO getDescDocumento() {
		return descDocumento;
	}

	public void setDescDocumento(DescDocumentoBO descDocumento) {
		this.descDocumento = descDocumento;
	}
	
	public void setNumeRag(Integer numeRag) {
		this.numeRag = numeRag;
	}

	public Integer getNumeRag() {
		return numeRag;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("anagAmminDem").append("='").append(getAnagAmminDem())
				.append("' ");
		buffer.append("anagRagionerieDem").append("='")
				.append(getAnagRagionerieDem()).append("' ");
		buffer.append("tipoDocumento").append("='").append(getTipoDocumento())
				.append("' ");
		buffer.append("sottoFascicoliRed").append("='")
				.append(getSottoFascicoliRed()).append("' ");
		buffer.append("numeVersion").append("='").append(getNumeVersion())
				.append("' ");
		buffer.append("codiGuidDocumentoTrasf").append("='")
				.append(getCodiGuidDocumentoTrasf()).append("' ");
		buffer.append("codiGuidDocProv").append("='")
				.append(getCodiGuidDocProv()).append("' ");
		buffer.append("codiGuidDocOrigProv").append("='")
				.append(getCodiGuidDocOrigProv()).append("' ");
		buffer.append("descTipoFlusso").append("='")
				.append(getDescTipoFlusso()).append("' ");
		buffer.append("statDocumento").append("='").append(getStatDocumento())
				.append("' ");
		buffer.append("codiProtocollo").append("='")
				.append(getCodiProtocollo()).append("' ");
		buffer.append("flagVisibilitaCdc01").append("='")
				.append(getFlagVisibilitaCdc01()).append("' ");
		buffer.append("dataDocumento").append("='").append(getDataDocumento())
				.append("' ");
		buffer.append("dataArrivo").append("='").append(getDataArrivo())
				.append("' ");
		buffer.append("dataChiusura").append("='").append(getDataChiusura())
				.append("' ");
		buffer.append("dataAggiornamento").append("='")
				.append(getDataAggiornamento()).append("' ");
		buffer.append("dataAnnullamento").append("='")
				.append(getDataAnnullamento()).append("' ");
		buffer.append("descFilename").append("='").append(getDescFilename())
				.append("' ");
		buffer.append("codiMimeTypeOrig").append("='")
				.append(getCodiMimeTypeOrig()).append("' ");
		buffer.append("codiHash").append("='").append(getCodiHash())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DocumentiRedBO other = (DocumentiRedBO) obj;
		if (anagAmminDem == null) {
			if (other.anagAmminDem != null)
				return false;
		} else if (!anagAmminDem.equals(other.anagAmminDem))
			return false;
		if (anagRagionerieDem == null) {
			if (other.anagRagionerieDem != null)
				return false;
		} else if (!anagRagionerieDem.equals(other.anagRagionerieDem))
			return false;
		if (codiGuidDocOrigProv == null) {
			if (other.codiGuidDocOrigProv != null)
				return false;
		} else if (!codiGuidDocOrigProv.equals(other.codiGuidDocOrigProv))
			return false;
		if (codiGuidDocProv == null) {
			if (other.codiGuidDocProv != null)
				return false;
		} else if (!codiGuidDocProv.equals(other.codiGuidDocProv))
			return false;
		if (codiGuidDocumentoTrasf == null) {
			if (other.codiGuidDocumentoTrasf != null)
				return false;
		} else if (!codiGuidDocumentoTrasf.equals(other.codiGuidDocumentoTrasf))
			return false;
		if (codiHash == null) {
			if (other.codiHash != null)
				return false;
		} else if (!codiHash.equals(other.codiHash))
			return false;
		if (codiIdRed == null) {
			if (other.codiIdRed != null)
				return false;
		} else if (!codiIdRed.equals(other.codiIdRed))
			return false;
		if (codiMimeTypeOrig == null) {
			if (other.codiMimeTypeOrig != null)
				return false;
		} else if (!codiMimeTypeOrig.equals(other.codiMimeTypeOrig))
			return false;
		if (codiProtocollo == null) {
			if (other.codiProtocollo != null)
				return false;
		} else if (!codiProtocollo.equals(other.codiProtocollo))
			return false;
		if (dataAggiornamento == null) {
			if (other.dataAggiornamento != null)
				return false;
		} else if (!dataAggiornamento.equals(other.dataAggiornamento))
			return false;
		if (dataAnnullamento == null) {
			if (other.dataAnnullamento != null)
				return false;
		} else if (!dataAnnullamento.equals(other.dataAnnullamento))
			return false;
		if (dataArrivo == null) {
			if (other.dataArrivo != null)
				return false;
		} else if (!dataArrivo.equals(other.dataArrivo))
			return false;
		if (dataChiusura == null) {
			if (other.dataChiusura != null)
				return false;
		} else if (!dataChiusura.equals(other.dataChiusura))
			return false;
		if (dataDocumento == null) {
			if (other.dataDocumento != null)
				return false;
		} else if (!dataDocumento.equals(other.dataDocumento))
			return false;
		if (descDocumento == null) {
			if (other.descDocumento != null)
				return false;
		} else if (!descDocumento.equals(other.descDocumento))
			return false;
		if (descFilename == null) {
			if (other.descFilename != null)
				return false;
		} else if (!descFilename.equals(other.descFilename))
			return false;
		if (descTipoFlusso == null) {
			if (other.descTipoFlusso != null)
				return false;
		} else if (!descTipoFlusso.equals(other.descTipoFlusso))
			return false;
		if (flagVisibilitaCdc01 == null) {
			if (other.flagVisibilitaCdc01 != null)
				return false;
		} else if (!flagVisibilitaCdc01.equals(other.flagVisibilitaCdc01))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (sottoFascicoliRed == null) {
			if (other.sottoFascicoliRed != null)
				return false;
		} else if (!sottoFascicoliRed.equals(other.sottoFascicoliRed))
			return false;
		if (statDocumento == null) {
			if (other.statDocumento != null)
				return false;
		} else if (!statDocumento.equals(other.statDocumento))
			return false;
		if (tipoDocumento == null) {
			if (other.tipoDocumento != null)
				return false;
		} else if (!tipoDocumento.equals(other.tipoDocumento))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((anagAmminDem == null) ? 0 : anagAmminDem.hashCode());
		result = prime
				* result
				+ ((anagRagionerieDem == null) ? 0 : anagRagionerieDem
						.hashCode());
		result = prime
				* result
				+ ((codiGuidDocOrigProv == null) ? 0 : codiGuidDocOrigProv
						.hashCode());
		result = prime * result
				+ ((codiGuidDocProv == null) ? 0 : codiGuidDocProv.hashCode());
		result = prime
				* result
				+ ((codiGuidDocumentoTrasf == null) ? 0 : codiGuidDocumentoTrasf
						.hashCode());
		result = prime * result
				+ ((codiHash == null) ? 0 : codiHash.hashCode());
		result = prime * result
				+ ((codiIdRed == null) ? 0 : codiIdRed.hashCode());
		result = prime
				* result
				+ ((codiMimeTypeOrig == null) ? 0 : codiMimeTypeOrig.hashCode());
		result = prime * result
				+ ((codiProtocollo == null) ? 0 : codiProtocollo.hashCode());
		result = prime
				* result
				+ ((dataAggiornamento == null) ? 0 : dataAggiornamento
						.hashCode());
		result = prime
				* result
				+ ((dataAnnullamento == null) ? 0 : dataAnnullamento.hashCode());
		result = prime * result
				+ ((dataArrivo == null) ? 0 : dataArrivo.hashCode());
		result = prime * result
				+ ((dataChiusura == null) ? 0 : dataChiusura.hashCode());
		result = prime * result
				+ ((dataDocumento == null) ? 0 : dataDocumento.hashCode());
		result = prime * result
				+ ((descDocumento == null) ? 0 : descDocumento.hashCode());
		result = prime * result
				+ ((descFilename == null) ? 0 : descFilename.hashCode());
		result = prime * result
				+ ((descTipoFlusso == null) ? 0 : descTipoFlusso.hashCode());
		result = prime
				* result
				+ ((flagVisibilitaCdc01 == null) ? 0 : flagVisibilitaCdc01
						.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime
				* result
				+ ((sottoFascicoliRed == null) ? 0 : sottoFascicoliRed
						.hashCode());
		result = prime * result
				+ ((statDocumento == null) ? 0 : statDocumento.hashCode());
		result = prime * result
				+ ((tipoDocumento == null) ? 0 : tipoDocumento.hashCode());
		return result;
	}

	


	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
