package it.mef.bilancio.demdec.to;

// Generated 7-set-2010 11.52.15 by Hibernate Tools 3.2.4.GA


import java.io.Serializable;

/**
 * ApplicationTO generated by hbm2java
 */
public class CronologicoSearchTO extends AbstractDemTO implements Serializable  {//INIZIO METODO
	private static final long serialVersionUID = 1L;
	// Applicazione //
	private Integer sequIdApplication;
	private String  codiApplication;
	private String  descApplication;
	// Categoria //
	private Integer sequIdHelpCategoria;
	private String  codiHelpCategoria;
	// Funzione //
	private String codiNome;
	private String descDescr;
	private String codiMenu;
	
	public Integer getSequIdApplication() {//INIZIO METODO
		return sequIdApplication;
	}//FINE METODO
	public void setSequIdApplication(Integer sequIdApplication) {//INIZIO METODO
		this.sequIdApplication = sequIdApplication;
	}//FINE METODO
	public String getCodiApplication() {//INIZIO METODO
		return codiApplication;
	}//FINE METODO
	public void setCodiApplication(String codiApplication) {//INIZIO METODO
		this.codiApplication = codiApplication;
	}//FINE METODO
	public String getDescApplication() {//INIZIO METODO
		return descApplication;
	}//FINE METODO
	public void setDescApplication(String descApplication) {//INIZIO METODO
		this.descApplication = descApplication;
	}//FINE METODO
	public Integer getSequIdHelpCategoria() {//INIZIO METODO
		return sequIdHelpCategoria;
	}//FINE METODO
	public void setSequIdHelpCategoria(Integer sequIdHelpCategoria) {//INIZIO METODO
		this.sequIdHelpCategoria = sequIdHelpCategoria;
	}//FINE METODO
	public String getCodiHelpCategoria() {//INIZIO METODO
		return codiHelpCategoria;
	}//FINE METODO
	public void setCodiHelpCategoria(String codiHelpCategoria) {//INIZIO METODO
		this.codiHelpCategoria = codiHelpCategoria;
	}//FINE METODO
	public String getCodiNome() {//INIZIO METODO
		return codiNome;
	}//FINE METODO
	public void setCodiNome(String codiNome) {//INIZIO METODO
		this.codiNome = codiNome;
	}//FINE METODO
	public String getDescDescr() {//INIZIO METODO
		return descDescr;
	}//FINE METODO
	public void setDescDescr(String descDescr) {//INIZIO METODO
		this.descDescr = descDescr;
	}//FINE METODO
	public String getCodiMenu() {//INIZIO METODO
		return codiMenu;
	}//FINE METODO
	public void setCodiMenu(String codiMenu) {//INIZIO METODO
		this.codiMenu = codiMenu;
	}//FINE METODO
	
		

}//FINE METODO
