package it.almavivaitalia.bilancio.commons.bo;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1


/**
 * AnagTipoFlussoBO generated by hbm2java
 */
public class AnagTipoFlussoBO extends AbstractCommonBO implements
		java.io.Serializable {

	private String id;
	private String descTipoFlusso;

	public AnagTipoFlussoBO() {
	}

	public AnagTipoFlussoBO(String id) {
		this.id = id;
	}

	public AnagTipoFlussoBO(String id, String descTipoFlusso) {
		this.id = id;
		this.descTipoFlusso = descTipoFlusso;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDescTipoFlusso() {
		return this.descTipoFlusso;
	}

	public void setDescTipoFlusso(String descTipoFlusso) {
		this.descTipoFlusso = descTipoFlusso;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("descTipoFlusso").append("='")
				.append(getDescTipoFlusso()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnagTipoFlussoBO))
			return false;
		AnagTipoFlussoBO castOther = (AnagTipoFlussoBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getDescTipoFlusso() == castOther.getDescTipoFlusso()) || (this
						.getDescTipoFlusso() != null
						&& castOther.getDescTipoFlusso() != null && this
						.getDescTipoFlusso().equals(
								castOther.getDescTipoFlusso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getDescTipoFlusso() == null ? 0 : this.getDescTipoFlusso()
						.hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
