package it.almavivaitalia.bilancio.commons.to;

import it.almavivaitalia.bilancio.commons.utils.StringUtil;

// Generated 5-giu-2015 12.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * AnagAmminDemBOId generated by hbm2java
 */
public class AnagAmminDemTOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Short fkAnnoEse;
	private Integer numeStp;
	private Integer numeApp;

	public AnagAmminDemTOId() {
	}

	public AnagAmminDemTOId(Short fkAnnoEse, Integer numeStp, Integer numeApp) {
		this.fkAnnoEse = fkAnnoEse;
		this.numeStp = numeStp;
		this.numeApp = numeApp;
	}

	public Short getFkAnnoEse() {
		return this.fkAnnoEse;
	}

	public void setFkAnnoEse(Short fkAnnoEse) {
		this.fkAnnoEse = fkAnnoEse;
	}

	public Integer getNumeStp() {
		return this.numeStp;
	}

	public void setNumeStp(Integer numeStp) {
		this.numeStp = numeStp;
	}

	public String getNumeStpFormatted() {
		return StringUtil.leftPad(""+this.numeStp, 2, "0");
	}

	public Integer getNumeApp() {
		return this.numeApp;
	}

	public void setNumeApp(Integer numeApp) {
		this.numeApp = numeApp;
	}

	public String getNumeAppFormatted() {
		return StringUtil.leftPad(""+this.numeApp, 1, "0");
	}

	public String getAmmin(){
		return numeStp==0?"000":StringUtil.leftPad(""+this.numeStp, 2, "0") + StringUtil.leftPad(""+this.numeApp, 1, "0");
	}
	
	
	public void setAmmin(String ammin){
		this.numeStp= Integer.valueOf(ammin.substring(0, 2));
		this.numeApp= Integer.valueOf(ammin.substring(2));
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnagAmminDemTOId))
			return false;
		AnagAmminDemTOId castOther = (AnagAmminDemTOId) other;

		return ((this.getFkAnnoEse() == castOther.getFkAnnoEse()) || (this
				.getFkAnnoEse() != null && castOther.getFkAnnoEse() != null && this
				.getFkAnnoEse().equals(castOther.getFkAnnoEse())))
				&& ((this.getNumeStp() == castOther.getNumeStp()) || (this
						.getNumeStp() != null && castOther.getNumeStp() != null && this
						.getNumeStp().equals(castOther.getNumeStp())))
				&& ((this.getNumeApp() == castOther.getNumeApp()) || (this
						.getNumeApp() != null && castOther.getNumeApp() != null && this
						.getNumeApp().equals(castOther.getNumeApp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFkAnnoEse() == null ? 0 : this.getFkAnnoEse().hashCode());
		result = 37 * result
				+ (getNumeStp() == null ? 0 : this.getNumeStp().hashCode());
		result = 37 * result
				+ (getNumeApp() == null ? 0 : this.getNumeApp().hashCode());
		return result;
	}

}
