package it.mef.bilancio.demdec.to;

import it.almavivaitalia.bilancio.commons.to.EserciziTO;

import it.almavivaitalia.bilancio.commons.to.AbstractCommonTO;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1


/**
 * AnagRagionerieDemBO generated by hbm2java
 */
public class AnagRagionerieDemTO extends AbstractCommonTO implements
		java.io.Serializable {

	private AnagRagionerieDemTOId id;
	private EserciziTO eserciziDem;
	private String descRag;
	private String statTipoRag;

	public AnagRagionerieDemTO() {
	}

	public AnagRagionerieDemTO(AnagRagionerieDemTOId id) {
		this.id = id;
	}

	public AnagRagionerieDemTO(AnagRagionerieDemTOId id,
			EserciziTO eserciziDem, String descRag, String statTipoRag) {
		this.id = id;
		this.eserciziDem = eserciziDem;
		this.descRag = descRag;
		this.statTipoRag = statTipoRag;
	}

	public AnagRagionerieDemTOId getId() {
		return this.id;
	}

	public void setId(AnagRagionerieDemTOId id) {
		this.id = id;
	}

	public EserciziTO getEserciziDem() {
		return this.eserciziDem;
	}

	public void setEserciziDem(EserciziTO eserciziDem) {
		this.eserciziDem = eserciziDem;
	}

	public String getDescRag() {
		return this.descRag;
	}

	public void setDescRag(String descRag) {
		this.descRag = descRag;
	}

	public String getStatTipoRag() {
		return this.statTipoRag;
	}

	public void setStatTipoRag(String statTipoRag) {
		this.statTipoRag = statTipoRag;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("eserciziDem").append("='").append(getEserciziDem())
				.append("' ");
		buffer.append("descRag").append("='").append(getDescRag()).append("' ");
		buffer.append("statTipoRag").append("='").append(getStatTipoRag())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnagRagionerieDemTO))
			return false;
		AnagRagionerieDemTO castOther = (AnagRagionerieDemTO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getEserciziDem() == castOther.getEserciziDem()) || (this
						.getEserciziDem() != null
						&& castOther.getEserciziDem() != null && this
						.getEserciziDem().equals(castOther.getEserciziDem())))
				&& ((this.getDescRag() == castOther.getDescRag()) || (this
						.getDescRag() != null && castOther.getDescRag() != null && this
						.getDescRag().equals(castOther.getDescRag())))
				&& ((this.getStatTipoRag() == castOther.getStatTipoRag()) || (this
						.getStatTipoRag() != null
						&& castOther.getStatTipoRag() != null && this
						.getStatTipoRag().equals(castOther.getStatTipoRag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getEserciziDem() == null ? 0 : this.getEserciziDem()
						.hashCode());
		result = 37 * result
				+ (getDescRag() == null ? 0 : this.getDescRag().hashCode());
		result = 37
				* result
				+ (getStatTipoRag() == null ? 0 : this.getStatTipoRag()
						.hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
