package it.mef.bilancio.demdec.to;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1


/**
 * AnagMetodoFirmaBO generated by hbm2java
 */
public class AnagMetodoFirmaTO extends AbstractDemTO implements
		java.io.Serializable {

	private String id;
	private String descMetodoFirma;

	public AnagMetodoFirmaTO() {
	}

	public AnagMetodoFirmaTO(String id, String descMetodoFirma) {
		this.id = id;
		this.descMetodoFirma = descMetodoFirma;
	}

	public AnagMetodoFirmaTO(String id) {
		this.id = id;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDescMetodoFirma() {
		return this.descMetodoFirma;
	}

	public void setDescMetodoFirma(String descMetodoFirma) {
		this.descMetodoFirma = descMetodoFirma;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("descMetodoFirma").append("='")
				.append(getDescMetodoFirma()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnagMetodoFirmaTO))
			return false;
		AnagMetodoFirmaTO castOther = (AnagMetodoFirmaTO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getDescMetodoFirma() == castOther
						.getDescMetodoFirma()) || (this.getDescMetodoFirma() != null
						&& castOther.getDescMetodoFirma() != null && this
						.getDescMetodoFirma().equals(
								castOther.getDescMetodoFirma())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getDescMetodoFirma() == null ? 0 : this.getDescMetodoFirma()
						.hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
