package it.mef.bilancio.demdec.to;

// Generated 7-set-2010 11.52.15 by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.util.Date;


/**
 * ApplicationTO generated by hbm2java
 */
public class CronologicoTO extends AbstractDemTO implements Serializable  {//INIZIO METODO
	private static final long serialVersionUID = 1L;
	
	private Short annoEseCap;
	private Integer numeStpCap;
	private Integer numeAppCap;
	private Integer numeEosCap;
	private Short numeNumCap;
	private Integer numePg;
	private String descAmm;
	private Short annoEseAut;
	private Integer numeTipoAut;
	private Integer numeNumAut;
	private Integer numeArtAut;
	private Integer numeSubArtAut;
	private Integer numeCommaAut;
	private Integer numeSubCommaAut;
	private String codiPuntoAut;
	private Integer numeSubPuntoAut;
	private Short annoEseStr;
	private Integer numeTipoStr;
	private Integer numeNumStr;
	private String descStrumento;
	private String descStrumentoTesto;
	private Short annoEseSst;
	private Integer numeTipoSst;
	private Integer numeNumSst;
	private String descSottoStrumento;	
	private String descUtente;
	private String textNote;
	private Date orarOperaz;
	private Short annoEsePar;
	private Short annoPrimaiscPar;
	private Integer numePrimaiscPar;
	private Short annoPlPle;
	private Short numePlPle;
	private Date dataOperaz;
	private Integer vocCodiId;
	private Integer traCodiCodice;
	private String descAutor;
	private String descAutorTesto;
	
	public Integer getTraCodiCodice() {//INIZIO METODO
		return traCodiCodice;
	}//FINE METODO
	public void setTraCodiCodice(Integer traCodiCodice) {//INIZIO METODO
		this.traCodiCodice = traCodiCodice;
	}//FINE METODO
	public Integer getVocCodiId() {//INIZIO METODO
		return vocCodiId;
	}//FINE METODO
	public void setVocCodiId(Integer vocCodiId) {//INIZIO METODO
		this.vocCodiId = vocCodiId;
	}//FINE METODO
	public Short getAnnoEseCap() {//INIZIO METODO
		return annoEseCap;
	}//FINE METODO
	public void setAnnoEseCap(Short annoEseCap) {//INIZIO METODO
		this.annoEseCap = annoEseCap;
	}//FINE METODO
	public Integer getNumeStpCap() {//INIZIO METODO
		return numeStpCap;
	}//FINE METODO
	public void setNumeStpCap(Integer numeStpCap) {//INIZIO METODO
		this.numeStpCap = numeStpCap;
	}//FINE METODO
	public Integer getNumeAppCap() {//INIZIO METODO
		return numeAppCap;
	}//FINE METODO
	public void setNumeAppCap(Integer numeAppCap) {//INIZIO METODO
		this.numeAppCap = numeAppCap;
	}//FINE METODO
	public Integer getNumeEosCap() {//INIZIO METODO
		return numeEosCap;
	}//FINE METODO
	public void setNumeEosCap(Integer numeEosCap) {//INIZIO METODO
		this.numeEosCap = numeEosCap;
	}//FINE METODO
	public Short getNumeNumCap() {//INIZIO METODO
		return numeNumCap;
	}//FINE METODO
	public void setNumeNumCap(Short numeNumCap) {//INIZIO METODO
		this.numeNumCap = numeNumCap;
	}//FINE METODO
	public Integer getNumePg() {//INIZIO METODO
		return numePg;
	}//FINE METODO
	public void setNumePg(Integer numePg) {//INIZIO METODO
		this.numePg = numePg;
	}//FINE METODO
	public Short getAnnoEseAut() {//INIZIO METODO
		return annoEseAut;
	}//FINE METODO
	public void setAnnoEseAut(Short annoEseAut) {//INIZIO METODO
		this.annoEseAut = annoEseAut;
	}//FINE METODO
	public Integer getNumeTipoAut() {//INIZIO METODO
		return numeTipoAut;
	}//FINE METODO
	public void setNumeTipoAut(Integer numeTipoAut) {//INIZIO METODO
		this.numeTipoAut = numeTipoAut;
	}//FINE METODO
	public Integer getNumeNumAut() {//INIZIO METODO
		return numeNumAut;
	}//FINE METODO
	public void setNumeNumAut(Integer numeNumAut) {//INIZIO METODO
		this.numeNumAut = numeNumAut;
	}//FINE METODO
	public Integer getNumeArtAut() {//INIZIO METODO
		return numeArtAut;
	}//FINE METODO
	public void setNumeArtAut(Integer numeArtAut) {//INIZIO METODO
		this.numeArtAut = numeArtAut;
	}//FINE METODO
	public Integer getNumeSubArtAut() {//INIZIO METODO
		return numeSubArtAut;
	}//FINE METODO
	public void setNumeSubArtAut(Integer numeSubArtAut) {//INIZIO METODO
		this.numeSubArtAut = numeSubArtAut;
	}//FINE METODO
	public Integer getNumeCommaAut() {//INIZIO METODO
		return numeCommaAut;
	}//FINE METODO
	public void setNumeCommaAut(Integer numeCommaAut) {//INIZIO METODO
		this.numeCommaAut = numeCommaAut;
	}//FINE METODO
	public Integer getNumeSubCommaAut() {//INIZIO METODO
		return numeSubCommaAut;
	}//FINE METODO
	public void setNumeSubCommaAut(Integer numeSubCommaAut) {//INIZIO METODO
		this.numeSubCommaAut = numeSubCommaAut;
	}//FINE METODO
	public String getCodiPuntoAut() {//INIZIO METODO
		return codiPuntoAut;
	}//FINE METODO
	public void setCodiPuntoAut(String codiPuntoAut) {//INIZIO METODO
		this.codiPuntoAut = codiPuntoAut;
	}//FINE METODO
	public Integer getNumeSubPuntoAut() {//INIZIO METODO
		return numeSubPuntoAut;
	}//FINE METODO
	public void setNumeSubPuntoAut(Integer numeSubPuntoAut) {//INIZIO METODO
		this.numeSubPuntoAut = numeSubPuntoAut;
	}//FINE METODO
	public Short getAnnoEseStr() {//INIZIO METODO
		return annoEseStr;
	}//FINE METODO
	public void setAnnoEseStr(Short annoEseStr) {//INIZIO METODO
		this.annoEseStr = annoEseStr;
	}//FINE METODO
	public Integer getNumeTipoStr() {//INIZIO METODO
		return numeTipoStr;
	}//FINE METODO
	public void setNumeTipoStr(Integer numeTipoStr) {//INIZIO METODO
		this.numeTipoStr = numeTipoStr;
	}//FINE METODO
	public Integer getNumeNumStr() {//INIZIO METODO
		return numeNumStr;
	}//FINE METODO
	public void setNumeNumStr(Integer numeNumStr) {//INIZIO METODO
		this.numeNumStr = numeNumStr;
	}//FINE METODO
	public Short getAnnoEseSst() {//INIZIO METODO
		return annoEseSst;
	}//FINE METODO
	public void setAnnoEseSst(Short annoEseSst) {//INIZIO METODO
		this.annoEseSst = annoEseSst;
	}//FINE METODO
	public Integer getNumeTipoSst() {//INIZIO METODO
		return numeTipoSst;
	}//FINE METODO
	public void setNumeTipoSst(Integer numeTipoSst) {//INIZIO METODO
		this.numeTipoSst = numeTipoSst;
	}//FINE METODO
	public Integer getNumeNumSst() {//INIZIO METODO
		return numeNumSst;
	}//FINE METODO
	public void setNumeNumSst(Integer numeNumSst) {//INIZIO METODO
		this.numeNumSst = numeNumSst;
	}//FINE METODO
	public Short getAnnoPrimaiscPar() {//INIZIO METODO
		return annoPrimaiscPar;
	}//FINE METODO
	public void setAnnoPrimaiscPar(Short annoPrimaiscPar) {//INIZIO METODO
		this.annoPrimaiscPar = annoPrimaiscPar;
	}//FINE METODO
	public Integer getNumePrimaiscPar() {//INIZIO METODO
		return numePrimaiscPar;
	}//FINE METODO
	public void setNumePrimaiscPar(Integer numePrimaiscPar) {//INIZIO METODO
		this.numePrimaiscPar = numePrimaiscPar;
	}//FINE METODO
	public Short getAnnoPlPle() {//INIZIO METODO
		return annoPlPle;
	}//FINE METODO
	public void setAnnoPlPle(Short annoPlPle) {//INIZIO METODO
		this.annoPlPle = annoPlPle;
	}//FINE METODO
	public Short getNumePlPle() {//INIZIO METODO
		return numePlPle;
	}//FINE METODO
	public void setNumePlPle(Short numePlPle) {//INIZIO METODO
		this.numePlPle = numePlPle;
	}//FINE METODO
	public String getDescUtente() {//INIZIO METODO
		return descUtente;
	}//FINE METODO
	public void setDescUtente(String descUtente) {//INIZIO METODO
		this.descUtente = descUtente;
	}//FINE METODO
	public String getTextNote() {//INIZIO METODO
		return textNote;
	}//FINE METODO
	public void setTextNote(String textNote) {//INIZIO METODO
		this.textNote = textNote;
	}//FINE METODO
	public Date getOrarOperaz() {//INIZIO METODO
		return orarOperaz;
	}//FINE METODO
	public void setOrarOperaz(Date orarOperaz) {//INIZIO METODO
		this.orarOperaz = orarOperaz;
	}//FINE METODO
	public Short getAnnoEsePar() {//INIZIO METODO
		return annoEsePar;
	}//FINE METODO
	public void setAnnoEsePar(Short annoEsePar) {//INIZIO METODO
		this.annoEsePar = annoEsePar;
	}//FINE METODO
	public Date getDataOperaz() {//INIZIO METODO
		return dataOperaz;
	}//FINE METODO
	public void setDataOperaz(Date dataOperaz) {//INIZIO METODO
		this.dataOperaz = dataOperaz;
	}//FINE METODO
	public String getDescAmm() {//INIZIO METODO
		return descAmm;
	}//FINE METODO
	public void setDescAmm(String descAmm) {//INIZIO METODO
		this.descAmm = descAmm;
	}//FINE METODO
	public String getDescStrumento() {//INIZIO METODO
		return descStrumento;
	}//FINE METODO
	public void setDescStrumento(String descStrumento) {//INIZIO METODO
		this.descStrumento = descStrumento;
	}//FINE METODO
	public String getDescSottoStrumento() {//INIZIO METODO
		return descSottoStrumento;
	}//FINE METODO
	public void setDescSottoStrumento(String descSottoStrumento) {//INIZIO METODO
		this.descSottoStrumento = descSottoStrumento;
	}//FINE METODO
	public String getDescStrumentoTesto() {//INIZIO METODO
		return descStrumentoTesto;
	}//FINE METODO
	public void setDescStrumentoTesto(String descStrumentoTesto) {//INIZIO METODO
		this.descStrumentoTesto = descStrumentoTesto;
	}//FINE METODO
	public String getDescAutor() {//INIZIO METODO
		return descAutor;
	}//FINE METODO
	public void setDescAutor(String descAutor) {//INIZIO METODO
		this.descAutor = descAutor;
	}//FINE METODO
	public String getDescAutorTesto() {//INIZIO METODO
		return descAutorTesto;
	}//FINE METODO
	public void setDescAutorTesto(String descAutorTesto) {//INIZIO METODO
		this.descAutorTesto = descAutorTesto;
	}//FINE METODO
	

}//FINE METODO
