package it.mef.bilancio.demdec.to;

import it.almavivaitalia.bilancio.commons.to.AnagAmminDemTO;

import java.util.List;

/**
 * MailTestiBO generated by hbm2java
 */
public class GestioneFadTO extends AbstractDemTO implements java.io.Serializable {

	private String chiamante;
//	String tipoOperazione;
	private Integer tipoDec;
	private Integer numeroDec;
	private Integer annoDec;
	private String descDec; 
	private Integer tipologiaDec; 
	private List<AnagAmminDemTO> ammList;
	private String ufficio;
//	String ucbRts;
	private List<AnagCdrDemTO> cdrList;
//	List<AmminRagDemTO> ragList;
//	Integer titolo;
	private Integer numPatr;
	private Integer flagNormativo;
	private String  ufficioCreatore;
	private String  codiUtente;
	private String  codiGuid;
	

	public String getChiamante() {
		return chiamante;
	}


	public void setChiamante(String chiamante) {
		this.chiamante = chiamante;
	}


//	public String getTipoOperazione() {
//		return tipoOperazione;
//	}
//
//
//	public void setTipoOperazione(String tipoOperazione) {
//		this.tipoOperazione = tipoOperazione;
//	}


	public Integer getTipoDec() {
		return tipoDec;
	}


	public void setTipoDec(Integer tipoDec) {
		this.tipoDec = tipoDec;
	}


	public Integer getNumeroDec() {
		return numeroDec;
	}


	public void setNumeroDec(Integer numeroDec) {
		this.numeroDec = numeroDec;
	}


	public Integer getAnnoDec() {
		return annoDec;
	}


	public void setAnnoDec(Integer annoDec) {
		this.annoDec = annoDec;
	}


	public String getDescDec() {
		return descDec;
	}


	public void setDescDec(String descDec) {
		this.descDec = descDec;
	}


	public Integer getTipologiaDec() {
		return tipologiaDec;
	}


	public void setTipologiaDec(Integer tipologiaDec) {
		this.tipologiaDec = tipologiaDec;
	}


	public List<AnagAmminDemTO> getAmmList() {
		return ammList;
	}


	public void setAmmList(List<AnagAmminDemTO> ammList) {
		this.ammList = ammList;
	}


	public String getUfficio() {
		return ufficio;
	}


	public void setUfficio(String ufficio) {
		this.ufficio = ufficio;
	}


//	public String getUcbRts() {
//		return ucbRts;
//	}
//
//
//	public void setUcbRts(String ucbRts) {
//		this.ucbRts = ucbRts;
//	}

//	public Integer getTitolo() {
//		return titolo;
//	}
//
//
//	public void setTitolo(Integer titolo) {
//		this.titolo = titolo;
//	}


	public Integer getNumPatr() {
		return numPatr;
	}


	public void setNumPatr(Integer numPatr) {
		this.numPatr = numPatr;
	}


	public Integer getFlagNormativo() {
		return flagNormativo;
	}


	public List<AnagCdrDemTO> getCdrList() {
		return cdrList;
	}


	public void setCdrList(List<AnagCdrDemTO> cdrList) {
		this.cdrList = cdrList;
	}


	public void setFlagNormativo(Integer flagNormativo) {
		this.flagNormativo = flagNormativo;
	}


	public String getUfficioCreatore() {
		return ufficioCreatore;
	}


	public void setUfficioCreatore(String ufficioCreatore) {
		this.ufficioCreatore = ufficioCreatore;
	}


	public String getCodiUtente() {
		return codiUtente;
	}


	public void setCodiUtente(String codiUtente) {
		this.codiUtente = codiUtente;
	}


//	public List<AmminRagDemTO> getRagList() {
//		return ragList;
//	}
//
//
//	public void setRagList(List<AmminRagDemTO> ragList) {
//		this.ragList = ragList;
//	}


	public String getCodiGuid() {
		return codiGuid;
	}


	public void setCodiGuid(String codiGuid) {
		this.codiGuid = codiGuid;
	}


	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}


