package it.mef.bilancio.demdec.to;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1


/**
 * SottoFascicoliRedBOId generated by hbm2java
 */
public class SottoFascicoliRedTOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2296037247688687002L;
	private String codiIdRed;
	private Long fkNumeIdFascicolo;

	public SottoFascicoliRedTOId() {
	}

	public SottoFascicoliRedTOId(String codiIdRed,
			Long fkNumeIdFascicolo) {
		this.codiIdRed = codiIdRed;
		this.fkNumeIdFascicolo = fkNumeIdFascicolo;
	}


	public String getCodiIdRed() {
		return this.codiIdRed;
	}

	public void setCodiIdRed(String codiIdRed) {
		this.codiIdRed = codiIdRed;
	}

	public Long getFkNumeIdFascicolo() {
		return this.fkNumeIdFascicolo;
	}

	public void setFkNumeIdFascicolo(Long fkNumeIdFascicolo) {
		this.fkNumeIdFascicolo = fkNumeIdFascicolo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SottoFascicoliRedTOId))
			return false;
		SottoFascicoliRedTOId castOther = (SottoFascicoliRedTOId) other;

		return ((this.getCodiIdRed() == castOther.getCodiIdRed()) || (this
						.getCodiIdRed() != null
						&& castOther.getCodiIdRed() != null && this
						.getCodiIdRed().equals(castOther.getCodiIdRed())))
				&& ((this.getFkNumeIdFascicolo() == castOther
						.getFkNumeIdFascicolo()) || (this
						.getFkNumeIdFascicolo() != null
						&& castOther.getFkNumeIdFascicolo() != null && this
						.getFkNumeIdFascicolo().equals(
								castOther.getFkNumeIdFascicolo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodiIdRed() == null ? 0 : this.getCodiIdRed().hashCode());
		result = 37
				* result
				+ (getFkNumeIdFascicolo() == null ? 0 : this
						.getFkNumeIdFascicolo().hashCode());
		return result;
	}

}
