package it.almavivaitalia.bilancio.commons.bo;

// Generated 22-lug-2015 15.41.08 by Hibernate Tools 3.4.0.CR1

import java.sql.Blob;
import java.util.Date;

/**
 * PecNotificheBO generated by hbm2java
 */
public class PecNotificheBO extends AbstractCommonBO implements
		java.io.Serializable {

	private String id;
	private PecMessaggiInviatiBO pecMessaggiInviati;
	private String tipoNotifica;
	private Date dataRicezione;
	private Blob notifica;

	public PecNotificheBO() {
	}

	public PecNotificheBO(String id) {
		this.id = id;
	}

	public PecNotificheBO(String id, PecMessaggiInviatiBO pecMessaggiInviati,
			String tipoNotifica, Date dataRicezione,
			Blob notifica) {
		this.id = id;
		this.pecMessaggiInviati = pecMessaggiInviati;
		this.tipoNotifica = tipoNotifica;
		this.dataRicezione = dataRicezione;
		this.notifica = notifica;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PecMessaggiInviatiBO getPecMessaggiInviati() {
		return this.pecMessaggiInviati;
	}

	public void setPecMessaggiInviati(PecMessaggiInviatiBO pecMessaggiInviati) {
		this.pecMessaggiInviati = pecMessaggiInviati;
	}

	public String getTipoNotifica() {
		return this.tipoNotifica;
	}

	public void setTipoNotifica(String tipoNotifica) {
		this.tipoNotifica = tipoNotifica;
	}

	public Date getDataRicezione() {
		return this.dataRicezione;
	}

	public void setDataRicezione(Date dataRicezione) {
		this.dataRicezione = dataRicezione;
	}

	public Blob getNotifica() {
		return this.notifica;
	}

	public void setNotifica(Blob notifica) {
		this.notifica = notifica;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("pecMessaggiInviati").append("='")
				.append(getPecMessaggiInviati()).append("' ");
		buffer.append("numeVersion").append("='").append(getNumeVersion())
				.append("' ");
		buffer.append("tipoNotifica").append("='").append(getTipoNotifica())
				.append("' ");
		buffer.append("dataRicezione").append("='").append(getDataRicezione())
				.append("' ");
		buffer.append("notifica").append("='").append(getNotifica())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PecNotificheBO))
			return false;
		PecNotificheBO castOther = (PecNotificheBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getPecMessaggiInviati() == castOther
						.getPecMessaggiInviati()) || (this
						.getPecMessaggiInviati() != null
						&& castOther.getPecMessaggiInviati() != null && this
						.getPecMessaggiInviati().equals(
								castOther.getPecMessaggiInviati())))
				&& ((this.getNumeVersion() == castOther.getNumeVersion()))
				&& ((this.getTipoNotifica() == castOther.getTipoNotifica()) || (this
						.getTipoNotifica() != null
						&& castOther.getTipoNotifica() != null && this
						.getTipoNotifica().equals(castOther.getTipoNotifica())))
				&& ((this.getDataRicezione() == castOther.getDataRicezione()) || (this
						.getDataRicezione() != null
						&& castOther.getDataRicezione() != null && this
						.getDataRicezione()
						.equals(castOther.getDataRicezione())))
				&& ((this.getNotifica() == castOther.getNotifica()) || (this
						.getNotifica() != null
						&& castOther.getNotifica() != null && this
						.getNotifica().equals(castOther.getNotifica())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getPecMessaggiInviati() == null ? 0 : this
						.getPecMessaggiInviati().hashCode());
		result = 37
				* result
				+ (getNumeVersion());
		result = 37
				* result
				+ (getTipoNotifica() == null ? 0 : this.getTipoNotifica()
						.hashCode());
		result = 37
				* result
				+ (getDataRicezione() == null ? 0 : this.getDataRicezione()
						.hashCode());
		result = 37 * result
				+ (getNotifica() == null ? 0 : this.getNotifica().hashCode());
		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
