package it.almavivaitalia.bilancio.commons.to;

// Generated 25-gen-2010 16.15.19 by Hibernate Tools 3.2.4.GA



import java.util.ArrayList;
import java.util.List;

/**
 * Item generated by hbm2java
 */
public class ItemTO extends AbstractCommonTO implements java.io.Serializable {

	private Long id;
	private ActionTO action;
	private ItemTO item;
	private MenuTO menu;
	private String codiItem;
	private List<ItemTO> itemList = new ArrayList<ItemTO>(0);
	private List<MenuTO> menuList = new ArrayList<MenuTO>(0);
	private Integer numeSequence;
	private boolean showChild;
	private String descItem;
	private String descItemEstesa;
	
	public boolean isShowChild() {
		return showChild;
	}
	public void setShowChild(boolean showChild) {
		this.showChild = showChild;
	}

	public Integer getNumeSequence() {
		return numeSequence;
	}




	public void setNumeSequence(Integer numeSequence) {
		this.numeSequence = numeSequence;
	}




	public ItemTO() {
	}




	public Long getId() {
		return id;
	}




	public void setId(Long id) {
		this.id = id;
	}




	public ActionTO getAction() {
		return this.action;
	}

	public void setAction(ActionTO action) {
		this.action = action;
	}

	public ItemTO getItem() {
		return this.item;
	}

	public void setItem(ItemTO item) {
		this.item = item;
	}

	public MenuTO getMenu() {
		return this.menu;
	}

	public void setMenu(MenuTO menu) {
		this.menu = menu;
	}

	public String getCodiItem() {
		return this.codiItem;
	}

	public void setCodiItem(String codiItem) {
		this.codiItem = codiItem;
	}


	public List<ItemTO> getItemList() {
		return itemList;
	}


	public void setItemList(List<ItemTO> itemList) {
		this.itemList = itemList;
	}


	public List<MenuTO> getMenuList() {
		return menuList;
	}


	public void setMenuList(List<MenuTO> menuList) {
		this.menuList = menuList;
	}

	

	public String getDescItem() {
		return descItem;
	}
	public void setDescItem(String descItem) {
		this.descItem = descItem;
	}
	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(
				Integer.toHexString(hashCode())).append(" [");
		buffer.append("sequIdItem").append("='").append(getId())
				.append("' ");
		buffer.append("action").append("='").append(getAction()).append("' ");
		buffer.append("item").append("='").append(getItem()).append("' ");
		buffer.append("menu").append("='").append(getMenu()).append("' ");
		buffer.append("codiItem").append("='").append(getCodiItem()).append(
				"' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemTO))
			return false;
		ItemTO castOther = (ItemTO) other;

		return ((this.getId() == castOther.getId()) || (this
				.getId() != null
				&& castOther.getId() != null && this.getId()
				.equals(castOther.getId())))
				&& ((this.getAction() == castOther.getAction()) || (this
						.getAction() != null
						&& castOther.getAction() != null && this.getAction()
						.equals(castOther.getAction())))
				&& ((this.getItem() == castOther.getItem()) || (this.getItem() != null
						&& castOther.getItem() != null && this.getItem()
						.equals(castOther.getItem())))
				&& ((this.getMenu() == castOther.getMenu()) || (this.getMenu() != null
						&& castOther.getMenu() != null && this.getMenu()
						.equals(castOther.getMenu())))
				&& ((this.getCodiItem() == castOther.getCodiItem()) || (this
						.getCodiItem() != null
						&& castOther.getCodiItem() != null && this
						.getCodiItem().equals(castOther.getCodiItem())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getId() == null ? 0 : this.getId()
						.hashCode());
		result = 37 * result
				+ (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result
				+ (getItem() == null ? 0 : this.getItem().hashCode());
		result = 37 * result
				+ (getMenu() == null ? 0 : this.getMenu().hashCode());
		result = 37 * result
				+ (getCodiItem() == null ? 0 : this.getCodiItem().hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

	
	// ADDED BUSINESS LOGIC
	public void addItem(ItemTO item){
		item.setItem(this);
		getItemList().add(item);
	}	

	
	private List<ProfiloTO> profiloList = new ArrayList<ProfiloTO>(0);
	
	
	// fa il merge delle due liste profilo (sulla lista A)
	protected void inheritProfiloList(ItemTO item) throws Throwable{
		for (ProfiloTO profiloTO : item.getProfiloList()) {
			if (!profiloList.contains(profiloTO)){
				profiloList.add(profiloTO);
			}
		}
	}
	
	
	
	public List<ProfiloTO> getProfiloList() {
		return profiloList;
	}


	public void setProfiloList(List<ProfiloTO> profiloList) {
		this.profiloList = profiloList;
	}

	public boolean checkPermission(String codiProfilo){
		ProfiloTO profilo = new ProfiloTO();
		profilo.setCodiProfilo(codiProfilo);
		return profiloList.contains(profilo);
	}
	public boolean checkPermission(Integer sequIdProfilo){
		ProfiloTO profilo = new ProfiloTO();
		profilo.setId(sequIdProfilo);
		return profiloList.contains(profilo);
	}
	public String getDescItemEstesa() {
		return descItemEstesa;
	}
	public void setDescItemEstesa(String descItemEstesa) {
		this.descItemEstesa = descItemEstesa;
	}
	
	
}
