package it.almavivaitalia.bilancio.commons.bo;
// Generated 11-apr-2016 13.25.46 by Hibernate Tools 3.4.0.CR1



/**
 * AnagTipoRiepilogoBO generated by hbm2java
 */
public class AnagTipoRiepilogoBO extends AbstractCommonBO implements java.io.Serializable {


     private Integer id;
     private String descTipoRiepilogo;
     private String codiAggr;

    public AnagTipoRiepilogoBO() {
    }

	
    public AnagTipoRiepilogoBO(String descTipoRiepilogo) {
        this.descTipoRiepilogo = descTipoRiepilogo;
    }
    public AnagTipoRiepilogoBO(String descTipoRiepilogo, String codiAggr) {
       this.descTipoRiepilogo = descTipoRiepilogo;
       this.codiAggr = codiAggr;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescTipoRiepilogo() {
        return this.descTipoRiepilogo;
    }
    
    public void setDescTipoRiepilogo(String descTipoRiepilogo) {
        this.descTipoRiepilogo = descTipoRiepilogo;
    }
    public String getCodiAggr() {
        return this.codiAggr;
    }
    
    public void setCodiAggr(String codiAggr) {
        this.codiAggr = codiAggr;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("descTipoRiepilogo").append("='").append(getDescTipoRiepilogo()).append("' ");			
      buffer.append("codiAggr").append("='").append(getCodiAggr()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AnagTipoRiepilogoBO) ) return false;
		 AnagTipoRiepilogoBO castOther = ( AnagTipoRiepilogoBO ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getDescTipoRiepilogo()==castOther.getDescTipoRiepilogo()) || ( this.getDescTipoRiepilogo()!=null && castOther.getDescTipoRiepilogo()!=null && this.getDescTipoRiepilogo().equals(castOther.getDescTipoRiepilogo()) ) )
 && ( (this.getCodiAggr()==castOther.getCodiAggr()) || ( this.getCodiAggr()!=null && castOther.getCodiAggr()!=null && this.getCodiAggr().equals(castOther.getCodiAggr()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getDescTipoRiepilogo() == null ? 0 : this.getDescTipoRiepilogo().hashCode() );
         result = 37 * result + ( getCodiAggr() == null ? 0 : this.getCodiAggr().hashCode() );
         return result;
   }   

  // The following is extra code specified in the hbm.xml files
private static final long serialVersionUID = 1L;
  // end of extra code specified in the hbm.xml files

}


