package it.almavivaitalia.bilancio.commons.bo;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1

/**
 * AnagCdrDemBOId generated by hbm2java
 */
public class AnagCdrDemBOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2247412162313175475L;
	private Short fkAnnoEse;
	private Integer fkNumeStp;
	private Integer fkNumeApp;
	private Short numeCdr;

	public AnagCdrDemBOId() {
	}

	public AnagCdrDemBOId(Short fkAnnoEse, Integer fkNumeStp,
			Integer fkNumeApp, Short numeCdr) {
		this.fkAnnoEse = fkAnnoEse;
		this.fkNumeStp = fkNumeStp;
		this.fkNumeApp = fkNumeApp;
		this.numeCdr = numeCdr;
	}

	public Short getFkAnnoEse() {
		return this.fkAnnoEse;
	}

	public void setFkAnnoEse(Short fkAnnoEse) {
		this.fkAnnoEse = fkAnnoEse;
	}

	public Integer getFkNumeStp() {
		return this.fkNumeStp;
	}

	public void setFkNumeStp(Integer fkNumeStp) {
		this.fkNumeStp = fkNumeStp;
	}

	public Integer getFkNumeApp() {
		return this.fkNumeApp;
	}

	public void setFkNumeApp(Integer fkNumeApp) {
		this.fkNumeApp = fkNumeApp;
	}

	public Short getNumeCdr() {
		return this.numeCdr;
	}

	public void setNumeCdr(Short numeCdr) {
		this.numeCdr = numeCdr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnagCdrDemBOId))
			return false;
		AnagCdrDemBOId castOther = (AnagCdrDemBOId) other;

		return ((this.getFkAnnoEse() == castOther.getFkAnnoEse()) || (this
				.getFkAnnoEse() != null && castOther.getFkAnnoEse() != null && this
				.getFkAnnoEse().equals(castOther.getFkAnnoEse())))
				&& ((this.getFkNumeStp() == castOther.getFkNumeStp()) || (this
						.getFkNumeStp() != null
						&& castOther.getFkNumeStp() != null && this
						.getFkNumeStp().equals(castOther.getFkNumeStp())))
				&& ((this.getFkNumeApp() == castOther.getFkNumeApp()) || (this
						.getFkNumeApp() != null
						&& castOther.getFkNumeApp() != null && this
						.getFkNumeApp().equals(castOther.getFkNumeApp())))
				&& ((this.getNumeCdr() == castOther.getNumeCdr()) || (this
						.getNumeCdr() != null && castOther.getNumeCdr() != null && this
						.getNumeCdr().equals(castOther.getNumeCdr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFkAnnoEse() == null ? 0 : this.getFkAnnoEse().hashCode());
		result = 37 * result
				+ (getFkNumeStp() == null ? 0 : this.getFkNumeStp().hashCode());
		result = 37 * result
				+ (getFkNumeApp() == null ? 0 : this.getFkNumeApp().hashCode());
		result = 37 * result
				+ (getNumeCdr() == null ? 0 : this.getNumeCdr().hashCode());
		return result;
	}

}
