package it.almavivaitalia.bilancio.commons.bo;

// Generated 22-lug-2015 15.42.05 by Hibernate Tools 3.4.0.CR1

/**
 * AnagFirmatariBO generated by hbm2java
 */
public class AnagFirmatariBO extends AbstractCommonBO implements
		java.io.Serializable {

	private String id;
	private String descFirmatario;
	private String codiTagFirma;
	private Integer fkSequIdProfilo;
	private String codiTipoFirma;
	private String descTipoFirma;
	private Integer flagPec01;
	private Integer flagAbilitaMail01;
	
	public AnagFirmatariBO() {
	}

	public AnagFirmatariBO(String id) {
	}

	public AnagFirmatariBO(String id, String descFirmatario,
			Integer fkSequIdProfilo, String codiTipoFirma, String descTipoFirma) {
		this.id = id;
		this.descFirmatario = descFirmatario;
		this.fkSequIdProfilo = fkSequIdProfilo;
		this.codiTipoFirma = codiTipoFirma;
		this.descTipoFirma = descTipoFirma;
	}

	public AnagFirmatariBO(String id, String descFirmatario, String codiTagFirma,
			Integer fkSequIdProfilo, String codiTipoFirma,
			String descTipoFirma, Integer flagPec01) {
		this.id = id;
		this.descFirmatario = descFirmatario;
		this.codiTagFirma = codiTagFirma;
		this.fkSequIdProfilo = fkSequIdProfilo;
		this.codiTipoFirma = codiTipoFirma;
		this.descTipoFirma = descTipoFirma;
		this.flagPec01 = flagPec01;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDescFirmatario() {
		return this.descFirmatario;
	}

	public void setDescFirmatario(String descFirmatario) {
		this.descFirmatario = descFirmatario;
	}

	public String getCodiTagFirma() {
		return this.codiTagFirma;
	}

	public void setCodiTagFirma(String codiTagFirma) {
		this.codiTagFirma = codiTagFirma;
	}

	public Integer getFkSequIdProfilo() {
		return this.fkSequIdProfilo;
	}

	public void setFkSequIdProfilo(Integer fkSequIdProfilo) {
		this.fkSequIdProfilo = fkSequIdProfilo;
	}

	public String getCodiTipoFirma() {
		return this.codiTipoFirma;
	}

	public void setCodiTipoFirma(String codiTipoFirma) {
		this.codiTipoFirma = codiTipoFirma;
	}

	public String getDescTipoFirma() {
		return this.descTipoFirma;
	}

	public void setDescTipoFirma(String descTipoFirma) {
		this.descTipoFirma = descTipoFirma;
	}

	public Integer getFlagPec01() {
		return this.flagPec01;
	}

	public void setFlagPec01(Integer flagPec01) {
		this.flagPec01 = flagPec01;
	}

	public Integer getFlagAbilitaMail01() {
		return flagAbilitaMail01;
	}

	public void setFlagAbilitaMail01(Integer flagAbilitaMail01) {
		this.flagAbilitaMail01 = flagAbilitaMail01;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codiTagFirma == null) ? 0 : codiTagFirma.hashCode());
		result = prime * result + ((codiTipoFirma == null) ? 0 : codiTipoFirma.hashCode());
		result = prime * result + ((descFirmatario == null) ? 0 : descFirmatario.hashCode());
		result = prime * result + ((descTipoFirma == null) ? 0 : descTipoFirma.hashCode());
		result = prime * result + ((fkSequIdProfilo == null) ? 0 : fkSequIdProfilo.hashCode());
		result = prime * result + ((flagAbilitaMail01 == null) ? 0 : flagAbilitaMail01.hashCode());
		result = prime * result + ((flagPec01 == null) ? 0 : flagPec01.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AnagFirmatariBO other = (AnagFirmatariBO) obj;
		if (codiTagFirma == null) {
			if (other.codiTagFirma != null)
				return false;
		} else if (!codiTagFirma.equals(other.codiTagFirma))
			return false;
		if (codiTipoFirma == null) {
			if (other.codiTipoFirma != null)
				return false;
		} else if (!codiTipoFirma.equals(other.codiTipoFirma))
			return false;
		if (descFirmatario == null) {
			if (other.descFirmatario != null)
				return false;
		} else if (!descFirmatario.equals(other.descFirmatario))
			return false;
		if (descTipoFirma == null) {
			if (other.descTipoFirma != null)
				return false;
		} else if (!descTipoFirma.equals(other.descTipoFirma))
			return false;
		if (fkSequIdProfilo == null) {
			if (other.fkSequIdProfilo != null)
				return false;
		} else if (!fkSequIdProfilo.equals(other.fkSequIdProfilo))
			return false;
		if (flagAbilitaMail01 == null) {
			if (other.flagAbilitaMail01 != null)
				return false;
		} else if (!flagAbilitaMail01.equals(other.flagAbilitaMail01))
			return false;
		if (flagPec01 == null) {
			if (other.flagPec01 != null)
				return false;
		} else if (!flagPec01.equals(other.flagPec01))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("numeVersion").append("='").append(getNumeVersion())
				.append("' ");
		buffer.append("descFirmatario").append("='")
				.append(getDescFirmatario()).append("' ");
		buffer.append("codiTagFirma").append("='").append(getCodiTagFirma())
				.append("' ");
		buffer.append("fkSequIdProfilo").append("='")
				.append(getFkSequIdProfilo()).append("' ");
		buffer.append("codiTipoFirma").append("='").append(getCodiTipoFirma())
				.append("' ");
		buffer.append("descTipoFirma").append("='").append(getDescTipoFirma())
				.append("' ");
		buffer.append("flagPec01").append("='").append(getFlagPec01())
				.append("' ");
		buffer.append("flagAbilitaMail01").append("='").append(getFlagAbilitaMail01())
		.append("' ");
		buffer.append("]");

		return buffer.toString();
	}
	

}
