package it.almavivaitalia.bilancio.commons.bo;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1


/**
 * AnagTipoDecretoBO generated by hbm2java
 */
public class AnagTipoDecretoBO extends AbstractCommonBO implements
		java.io.Serializable {

	private Integer id;
	private String descSigla;
	private String descTesto;

	public AnagTipoDecretoBO() {
	}

	public AnagTipoDecretoBO(Integer id) {
		this.id = id;
	}

	public AnagTipoDecretoBO(Integer id, String descSigla, String descTesto) {
		this.id = id;
		this.descSigla = descSigla;
		this.descTesto = descTesto;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescSigla() {
		return this.descSigla;
	}

	public void setDescSigla(String descSigla) {
		this.descSigla = descSigla;
	}

	public String getDescTesto() {
		return this.descTesto;
	}

	public void setDescTesto(String descTesto) {
		this.descTesto = descTesto;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("descSigla").append("='").append(getDescSigla())
				.append("' ");
		buffer.append("descTesto").append("='").append(getDescTesto())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnagTipoDecretoBO))
			return false;
		AnagTipoDecretoBO castOther = (AnagTipoDecretoBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getDescSigla() == castOther.getDescSigla()) || (this
						.getDescSigla() != null
						&& castOther.getDescSigla() != null && this
						.getDescSigla().equals(castOther.getDescSigla())))
				&& ((this.getDescTesto() == castOther.getDescTesto()) || (this
						.getDescTesto() != null
						&& castOther.getDescTesto() != null && this
						.getDescTesto().equals(castOther.getDescTesto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getDescSigla() == null ? 0 : this.getDescSigla().hashCode());
		result = 37 * result
				+ (getDescTesto() == null ? 0 : this.getDescTesto().hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
