package it.almavivaitalia.bilancio.commons.bo;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1


/**
 * AnagCdrDemBO generated by hbm2java
 */
public class AnagCdrDemBO extends AbstractCommonBO implements
		java.io.Serializable {

	private AnagCdrDemBOId id;
	private AnagAmminDemBO anagAmminDem;
	private String descCdr;

	public AnagCdrDemBO() {
	}

	public AnagCdrDemBO(AnagCdrDemBOId id, AnagAmminDemBO anagAmminDem,
			String descCdr) {
		this.id = id;
		this.anagAmminDem = anagAmminDem;
		this.descCdr = descCdr;
	}

	public AnagCdrDemBO(AnagCdrDemBOId id) {
		this.id = id;
	}

	public AnagCdrDemBOId getId() {
		return this.id;
	}

	public void setId(AnagCdrDemBOId id) {
		this.id = id;
	}

	public AnagAmminDemBO getAnagAmminDem() {
		return this.anagAmminDem;
	}

	public void setAnagAmminDem(AnagAmminDemBO anagAmminDem) {
		this.anagAmminDem = anagAmminDem;
	}

	public String getDescCdr() {
		return this.descCdr;
	}

	public void setDescCdr(String descCdr) {
		this.descCdr = descCdr;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("anagAmminDem").append("='").append(getAnagAmminDem())
				.append("' ");
		buffer.append("descCdr").append("='").append(getDescCdr()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnagCdrDemBO))
			return false;
		AnagCdrDemBO castOther = (AnagCdrDemBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getAnagAmminDem() == castOther.getAnagAmminDem()) || (this
						.getAnagAmminDem() != null
						&& castOther.getAnagAmminDem() != null && this
						.getAnagAmminDem().equals(castOther.getAnagAmminDem())))
				&& ((this.getDescCdr() == castOther.getDescCdr()) || (this
						.getDescCdr() != null && castOther.getDescCdr() != null && this
						.getDescCdr().equals(castOther.getDescCdr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getAnagAmminDem() == null ? 0 : this.getAnagAmminDem()
						.hashCode());
		result = 37 * result
				+ (getDescCdr() == null ? 0 : this.getDescCdr().hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
