package it.almavivaitalia.bilancio.commons.bo;

// Generated 20-lug-2010 15.50.55 by Hibernate Tools 3.2.4.GA

/**
 * CroDatiBOId generated by hbm2java
 */
public class CroDatiBOId implements  java.io.Serializable {

	private Integer codiId;
	private Short traCodiCodice;

	public CroDatiBOId() { //BEGIN
	}

	public CroDatiBOId(Integer codiId, Short traCodiCodice) { //BEGIN
		this.codiId = codiId;
		this.traCodiCodice = traCodiCodice;
	}

	public Integer getCodiId() { //BEGIN
		return this.codiId;
	}

	public void setCodiId(Integer codiId) { //BEGIN
		this.codiId = codiId;
	}

	public Short getTraCodiCodice() { //BEGIN
		return this.traCodiCodice;
	}

	public void setTraCodiCodice(Short traCodiCodice) { //BEGIN
		this.traCodiCodice = traCodiCodice;
	}

	public boolean equals(Object other) { //BEGIN
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CroDatiBOId))
			return false;
		CroDatiBOId castOther = (CroDatiBOId) other;

		return ((this.getCodiId() == castOther.getCodiId()) || (this
				.getCodiId() != null
				&& castOther.getCodiId() != null && this.getCodiId().equals(
				castOther.getCodiId())))
				&& ((this.getTraCodiCodice() == castOther.getTraCodiCodice()) || (this
						.getTraCodiCodice() != null
						&& castOther.getTraCodiCodice() != null && this
						.getTraCodiCodice()
						.equals(castOther.getTraCodiCodice())));
	}

	public int hashCode() { //BEGIN
		int result = 17;

		result = 37 * result
				+ (getCodiId() == null ? 0 : this.getCodiId().hashCode());
		result = 37
				* result
				+ (getTraCodiCodice() == null ? 0 : this.getTraCodiCodice()
						.hashCode());
		return result;
	}

    /*METRICHE*/

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@SuppressWarnings("unused")	
    private final static String securityMetricaLOCM1 = "LOCM";
    @SuppressWarnings("unused")	
    private final static String securityMetricaLOCM2 = "LOCM";
    @SuppressWarnings("unused")	
    private final static String securityMetricaLOCM3 = "LOCM"; 
    @SuppressWarnings("unused")	
    private final static String securityMetricaLOCM4 = "LOCM";
    @SuppressWarnings("unused")	
    private final static String securityMetricaLOCM5 = "LOCM";
    @SuppressWarnings("unused")	
    private final static String securityMetricaLOCM6 = "LOCM";

	
}
