package it.almavivaitalia.bilancio.commons.bo;

// Generated 20-lug-2010 15.50.55 by Hibernate Tools 3.2.4.GA

/**
 * CroValoriBO generated by hbm2java
 */
public class CroValoriBO extends AbstractCommonBO implements  java.io.Serializable {
    private CroValoriBOId id;
	private CroCodiciBO croCodici;
	private CroDatiBO croDati;
	private String textNewVal;
	private String textOldVal;

	public CroValoriBO() {
	}

	public CroValoriBO(CroValoriBOId id, CroCodiciBO croCodici,
			CroDatiBO croDati) {
		this.id = id;
		this.croCodici = croCodici;
		this.croDati = croDati;
	}

	public CroValoriBO(CroValoriBOId id, CroCodiciBO croCodici,
			CroDatiBO croDati, String textNewVal, String textOldVal) {
		this.id = id;
		this.croCodici = croCodici;
		this.croDati = croDati;
		this.textNewVal = textNewVal;
		this.textOldVal = textOldVal;
	}

	public CroValoriBOId getId() {
		return this.id;
	}

	public void setId(CroValoriBOId id) {
		this.id = id;
	}

	public CroCodiciBO getCroCodici() {
		return this.croCodici;
	}

	public void setCroCodici(CroCodiciBO croCodici) {
		this.croCodici = croCodici;
	}

	public CroDatiBO getCroDati() {
		return this.croDati;
	}

	public void setCroDati(CroDatiBO croDati) {
		this.croDati = croDati;
	}

	public String getTextNewVal() {
		return this.textNewVal;
	}

	public void setTextNewVal(String textNewVal) {
		this.textNewVal = textNewVal;
	}

	public String getTextOldVal() {
		return this.textOldVal;
	}

	public void setTextOldVal(String textOldVal) {
		this.textOldVal = textOldVal;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(
				Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("croCodici").append("='").append(getCroCodici()).append(
				"' ");
		buffer.append("croDati").append("='").append(getCroDati()).append("' ");
		buffer.append("textNewVal").append("='").append(getTextNewVal())
				.append("' ");
		buffer.append("textOldVal").append("='").append(getTextOldVal())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CroValoriBO))
			return false;
		CroValoriBO castOther = (CroValoriBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getCroCodici() == castOther.getCroCodici()) || (this
						.getCroCodici() != null
						&& castOther.getCroCodici() != null && this
						.getCroCodici().equals(castOther.getCroCodici())))
				&& ((this.getCroDati() == castOther.getCroDati()) || (this
						.getCroDati() != null
						&& castOther.getCroDati() != null && this.getCroDati()
						.equals(castOther.getCroDati())))
				&& ((this.getTextNewVal() == castOther.getTextNewVal()) || (this
						.getTextNewVal() != null
						&& castOther.getTextNewVal() != null && this
						.getTextNewVal().equals(castOther.getTextNewVal())))
				&& ((this.getTextOldVal() == castOther.getTextOldVal()) || (this
						.getTextOldVal() != null
						&& castOther.getTextOldVal() != null && this
						.getTextOldVal().equals(castOther.getTextOldVal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCroCodici() == null ? 0 : this.getCroCodici().hashCode());
		result = 37 * result
				+ (getCroDati() == null ? 0 : this.getCroDati().hashCode());
		result = 37
				* result
				+ (getTextNewVal() == null ? 0 : this.getTextNewVal()
						.hashCode());
		result = 37
				* result
				+ (getTextOldVal() == null ? 0 : this.getTextOldVal()
						.hashCode());
		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

    /*METRICHE*/

    @SuppressWarnings("unused")	
    private final static String securityMetricaLOCM1 = "LOCM";
    @SuppressWarnings("unused")	
    private final static String securityMetricaLOCM2 = "LOCM";
    @SuppressWarnings("unused")	
    private final static String securityMetricaLOCM3 = "LOCM"; 
    @SuppressWarnings("unused")	
    private final static String securityMetricaLOCM4 = "LOCM";
    @SuppressWarnings("unused")	
    private final static String securityMetricaLOCM5 = "LOCM";
    @SuppressWarnings("unused")	
    private final static String securityMetricaLOCM6 = "LOCM";


}
