package it.almavivaitalia.bilancio.commons.bo;
// Generated 13-nov-2015 17.10.08 by Hibernate Tools 3.4.0.CR1



/**
 * DescDocumentoBO generated by hbm2java
 */
public class DescDocumentoBO extends AbstractCommonBO implements java.io.Serializable {


     private String id;
     private String textDescrizione;
     private String codiTipoDocumento;
     private Integer flagVisibilitaCdc;

    public DescDocumentoBO() {
    }

    public DescDocumentoBO(String textDescrizione, String codiTipoDocumento) {
       this.textDescrizione = textDescrizione;
       this.codiTipoDocumento = codiTipoDocumento;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getTextDescrizione() {
        return this.textDescrizione;
    }
    
    public void setTextDescrizione(String textDescrizione) {
        this.textDescrizione = textDescrizione;
    }
    public String getCodiTipoDocumento() {
        return this.codiTipoDocumento;
    }
    
    public void setCodiTipoDocumento(String codiTipoDocumento) {
        this.codiTipoDocumento = codiTipoDocumento;
    }
 
    public Integer getFlagVisibilitaCdc() {
		return flagVisibilitaCdc;
	}

	public void setFlagVisibilitaCdc(Integer flagVisibilitaCdc) {
		this.flagVisibilitaCdc = flagVisibilitaCdc;
	}

	/**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("textDescrizione").append("='").append(getTextDescrizione()).append("' ");			
      buffer.append("codiTipoDocumento").append("='").append(getCodiTipoDocumento()).append("' ");			
      buffer.append("flagVisibilitaCdc").append("='").append(getFlagVisibilitaCdc()).append("' ");			
     buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DescDocumentoBO) ) return false;
		 DescDocumentoBO castOther = ( DescDocumentoBO ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
				 && ( (this.getTextDescrizione()==castOther.getTextDescrizione()) || ( this.getTextDescrizione()!=null && castOther.getTextDescrizione()!=null && this.getTextDescrizione().equals(castOther.getTextDescrizione()) ) )
				 && ( (this.getCodiTipoDocumento()==castOther.getCodiTipoDocumento()) || ( this.getCodiTipoDocumento()!=null && castOther.getCodiTipoDocumento()!=null && this.getCodiTipoDocumento().equals(castOther.getCodiTipoDocumento()) ) )
				 && ( (this.getFlagVisibilitaCdc()==castOther.getFlagVisibilitaCdc()) || ( this.getFlagVisibilitaCdc()!=null && castOther.getFlagVisibilitaCdc()!=null && this.getFlagVisibilitaCdc().equals(castOther.getFlagVisibilitaCdc()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getTextDescrizione() == null ? 0 : this.getTextDescrizione().hashCode() );
         result = 37 * result + ( getCodiTipoDocumento() == null ? 0 : this.getCodiTipoDocumento().hashCode() );
         result = 37 * result + ( getFlagVisibilitaCdc() == null ? 0 : this.getFlagVisibilitaCdc().hashCode() );
         
         
         return result;
   }   

  // The following is extra code specified in the hbm.xml files
private static final long serialVersionUID = 1L;
  // end of extra code specified in the hbm.xml files

}


