package it.almavivaitalia.bilancio.commons.bo;

// Generated 23-lug-2015 10.39.39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DocumentiBO generated by hbm2java
 */
public class DocumentiBO extends AbstractCommonBO implements
		java.io.Serializable {

	private DocumentiBOId id;
	private AnagAmminDemBO anagAmminDem;
	private AnagRagionerieDemBO anagRagionerieDem;
	private AnagMetodoFirmaBO anagMetodoFirma;
	private DescDocumentoBO descDocumento;
	private TipoDocumentoBO tipoDocumento;
	private FascicoliBO fascicoli;
	private String codiGuidDocumentoOrig;
	private String codiGuidDocumento;
	private String descTipoFlusso;
	private Integer statDocumento;
	private String statConversione;
	private String statEsitoConversione;
	private Short numeTitolo;
	private String codiProtocollo;
	private Integer flagVisibilitaCdc01;
	private Long numeTicketConservazione;
	private Date dataDocumento;
	private Date dataArrivo;
	private Date dataChiusura;
	private Date dataAggiornamento;
	private String fkCodiUtenteAgg;
	private Date dataAnnullamento;
	private String descFilename;
	private String codiGuidFascicolo;
	private String codiMimeTypeOrig;
	private String codiHash;
	
	private String textDescrizione;
    private String numeProtocollo;
    private String descTipoProtocollo;
    private Date dataProtocollo;

	public DocumentiBO() {
	}

	public DocumentiBO(DocumentiBOId id, TipoDocumentoBO tipoDocumento,
			FascicoliBO fascicoli, String codiGuidDocumentoOrig,
			String codiGuidDocumento, Integer statDocumento,
			String statConversione, String statEsitoConversione,
			Integer flagVisibilitaCdc01, String codiGuidFascicolo) {
		this.id = id;
		this.tipoDocumento = tipoDocumento;
		this.fascicoli = fascicoli;
		this.codiGuidDocumentoOrig = codiGuidDocumentoOrig;
		this.codiGuidDocumento = codiGuidDocumento;
		this.statDocumento = statDocumento;
		this.statConversione = statConversione;
		this.statEsitoConversione = statEsitoConversione;
		this.flagVisibilitaCdc01 = flagVisibilitaCdc01;
		this.codiGuidFascicolo = codiGuidFascicolo;
	}

	public DocumentiBO(DocumentiBOId id, AnagAmminDemBO anagAmminDem,
			AnagRagionerieDemBO anagRagionerieDem,
			AnagMetodoFirmaBO anagMetodoFirma, 
			TipoDocumentoBO tipoDocumento, FascicoliBO fascicoli,
			String codiGuidDocumentoOrig,
			String codiGuidDocumento, String descTipoFlusso,
			Integer statDocumento, String statConversione,
			String statEsitoConversione, Short numeTitolo,
			String codiProtocollo, Integer flagVisibilitaCdc01,
			Long numeTicketConservazione, Date dataDocumento, Date dataArrivo,
			Date dataChiusura, Date dataAggiornamento, String fkCodiUtenteAgg,
			Date dataAnnullamento, String descFilename,
			String codiGuidFascicolo, String codiMimeTypeOrig, String codiHash, String textDescrizione) {
		this.id = id;
		this.anagAmminDem = anagAmminDem;
		this.anagRagionerieDem = anagRagionerieDem;
		this.anagMetodoFirma = anagMetodoFirma;
		this.tipoDocumento = tipoDocumento;
		this.fascicoli = fascicoli;
		this.codiGuidDocumentoOrig = codiGuidDocumentoOrig;
		this.codiGuidDocumento = codiGuidDocumento;
		this.descTipoFlusso = descTipoFlusso;
		this.statDocumento = statDocumento;
		this.statConversione = statConversione;
		this.statEsitoConversione = statEsitoConversione;
		this.numeTitolo = numeTitolo;
		this.codiProtocollo = codiProtocollo;
		this.flagVisibilitaCdc01 = flagVisibilitaCdc01;
		this.numeTicketConservazione = numeTicketConservazione;
		this.dataDocumento = dataDocumento;
		this.dataArrivo = dataArrivo;
		this.dataChiusura = dataChiusura;
		this.dataAggiornamento = dataAggiornamento;
		this.fkCodiUtenteAgg = fkCodiUtenteAgg;
		this.dataAnnullamento = dataAnnullamento;
		this.descFilename = descFilename;
		this.codiGuidFascicolo = codiGuidFascicolo;
		this.codiMimeTypeOrig = codiMimeTypeOrig;
		this.codiHash = codiHash;
		
		this.textDescrizione = textDescrizione;
	}

	public DocumentiBOId getId() {
		return this.id;
	}

	public void setId(DocumentiBOId id) {
		this.id = id;
	}

	public AnagAmminDemBO getAnagAmminDem() {
		return this.anagAmminDem;
	}

	public void setAnagAmminDem(AnagAmminDemBO anagAmminDem) {
		this.anagAmminDem = anagAmminDem;
	}

	public AnagRagionerieDemBO getAnagRagionerieDem() {
		return this.anagRagionerieDem;
	}

	public void setAnagRagionerieDem(AnagRagionerieDemBO anagRagionerieDem) {
		this.anagRagionerieDem = anagRagionerieDem;
	}

	public AnagMetodoFirmaBO getAnagMetodoFirma() {
		return this.anagMetodoFirma;
	}

	public void setAnagMetodoFirma(AnagMetodoFirmaBO anagMetodoFirma) {
		this.anagMetodoFirma = anagMetodoFirma;
	}

	public TipoDocumentoBO getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumentoBO tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public FascicoliBO getFascicoli() {
		return this.fascicoli;
	}

	public void setFascicoli(FascicoliBO fascicoli) {
		this.fascicoli = fascicoli;
	}

	public String getCodiGuidDocumentoOrig() {
		return this.codiGuidDocumentoOrig;
	}

	public void setCodiGuidDocumentoOrig(String codiGuidDocumentoOrig) {
		this.codiGuidDocumentoOrig = codiGuidDocumentoOrig;
	}

	public String getCodiGuidDocumento() {
		return this.codiGuidDocumento;
	}

	public void setCodiGuidDocumento(String codiGuidDocumento) {
		this.codiGuidDocumento = codiGuidDocumento;
	}

	public String getDescTipoFlusso() {
		return this.descTipoFlusso;
	}

	public void setDescTipoFlusso(String descTipoFlusso) {
		this.descTipoFlusso = descTipoFlusso;
	}

	public Integer getStatDocumento() {
		return this.statDocumento;
	}

	public void setStatDocumento(Integer statDocumento) {
		this.statDocumento = statDocumento;
	}

	public String getStatConversione() {
		return this.statConversione;
	}

	public void setStatConversione(String statConversione) {
		this.statConversione = statConversione;
	}

	public String getStatEsitoConversione() {
		return this.statEsitoConversione;
	}

	public void setStatEsitoConversione(String statEsitoConversione) {
		this.statEsitoConversione = statEsitoConversione;
	}

	public Short getNumeTitolo() {
		return this.numeTitolo;
	}

	public void setNumeTitolo(Short numeTitolo) {
		this.numeTitolo = numeTitolo;
	}

	public String getCodiProtocollo() {
		return this.codiProtocollo;
	}

	public void setCodiProtocollo(String codiProtocollo) {
		this.codiProtocollo = codiProtocollo;
	}

	public Integer getFlagVisibilitaCdc01() {
		return this.flagVisibilitaCdc01;
	}

	public void setFlagVisibilitaCdc01(Integer flagVisibilitaCdc01) {
		this.flagVisibilitaCdc01 = flagVisibilitaCdc01;
	}

	public Long getNumeTicketConservazione() {
		return this.numeTicketConservazione;
	}

	public void setNumeTicketConservazione(Long numeTicketConservazione) {
		this.numeTicketConservazione = numeTicketConservazione;
	}

	public Date getDataDocumento() {
		return this.dataDocumento;
	}

	public void setDataDocumento(Date dataDocumento) {
		this.dataDocumento = dataDocumento;
	}

	public Date getDataArrivo() {
		return this.dataArrivo;
	}

	public void setDataArrivo(Date dataArrivo) {
		this.dataArrivo = dataArrivo;
	}

	public Date getDataChiusura() {
		return this.dataChiusura;
	}

	public void setDataChiusura(Date dataChiusura) {
		this.dataChiusura = dataChiusura;
	}

	public Date getDataAggiornamento() {
		return this.dataAggiornamento;
	}

	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	public String getFkCodiUtenteAgg() {
		return this.fkCodiUtenteAgg;
	}

	public void setFkCodiUtenteAgg(String fkCodiUtenteAgg) {
		this.fkCodiUtenteAgg = fkCodiUtenteAgg;
	}

	public Date getDataAnnullamento() {
		return this.dataAnnullamento;
	}

	public void setDataAnnullamento(Date dataAnnullamento) {
		this.dataAnnullamento = dataAnnullamento;
	}

	public String getDescFilename() {
		return this.descFilename;
	}

	public void setDescFilename(String descFilename) {
		this.descFilename = descFilename;
	}

	public String getCodiGuidFascicolo() {
		return this.codiGuidFascicolo;
	}

	public void setCodiGuidFascicolo(String codiGuidFascicolo) {
		this.codiGuidFascicolo = codiGuidFascicolo;
	}

	public String getCodiMimeTypeOrig() {
		return this.codiMimeTypeOrig;
	}

	public void setCodiMimeTypeOrig(String codiMimeTypeOrig) {
		this.codiMimeTypeOrig = codiMimeTypeOrig;
	}

	public String getCodiHash() {
		return this.codiHash;
	}

	public void setCodiHash(String codiHash) {
		this.codiHash = codiHash;
	}

	public String getTextDescrizione() {
		return textDescrizione;
	}

	public void setTextDescrizione(String textDescrizione) {
		this.textDescrizione = textDescrizione;
	}
	
    public String getNumeProtocollo() {
        return this.numeProtocollo;
    }
    
    public void setNumeProtocollo(String numeProtocollo) {
        this.numeProtocollo = numeProtocollo;
    }
    public String getDescTipoProtocollo() {
        return this.descTipoProtocollo;
    }
    
    public void setDescTipoProtocollo(String descTipoProtocollo) {
        this.descTipoProtocollo = descTipoProtocollo;
    }
    public Date getDataProtocollo() {
        return this.dataProtocollo;
    }
    
    public void setDataProtocollo(Date dataProtocollo) {
        this.dataProtocollo = dataProtocollo;
    }

    public DescDocumentoBO getDescDocumento() {
		return descDocumento;
	}

	public void setDescDocumento(DescDocumentoBO descDocumento) {
		this.descDocumento = descDocumento;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("anagAmminDem").append("='").append(getAnagAmminDem())
				.append("' ");
		buffer.append("anagRagionerieDem").append("='")
				.append(getAnagRagionerieDem()).append("' ");
		buffer.append("anagMetodoFirma").append("='")
				.append(getAnagMetodoFirma()).append("' ");
		buffer.append("tipoDocumento").append("='").append(getTipoDocumento())
				.append("' ");
		buffer.append("fascicoli").append("='").append(getFascicoli())
				.append("' ");
		buffer.append("numeVersion").append("='").append(getNumeVersion())
				.append("' ");
		buffer.append("codiGuidDocumentoOrig").append("='")
				.append(getCodiGuidDocumentoOrig()).append("' ");
		buffer.append("codiGuidDocumento").append("='")
				.append(getCodiGuidDocumento()).append("' ");
		buffer.append("descTipoFlusso").append("='")
				.append(getDescTipoFlusso()).append("' ");
		buffer.append("statDocumento").append("='").append(getStatDocumento())
				.append("' ");
		buffer.append("statConversione").append("='")
				.append(getStatConversione()).append("' ");
		buffer.append("statEsitoConversione").append("='")
				.append(getStatEsitoConversione()).append("' ");
		buffer.append("numeTitolo").append("='").append(getNumeTitolo())
				.append("' ");
		buffer.append("codiProtocollo").append("='")
				.append(getCodiProtocollo()).append("' ");
		buffer.append("flagVisibilitaCdc01").append("='")
				.append(getFlagVisibilitaCdc01()).append("' ");
		buffer.append("numeTicketConservazione").append("='")
				.append(getNumeTicketConservazione()).append("' ");
		buffer.append("dataDocumento").append("='").append(getDataDocumento())
				.append("' ");
		buffer.append("dataArrivo").append("='").append(getDataArrivo())
				.append("' ");
		buffer.append("dataChiusura").append("='").append(getDataChiusura())
				.append("' ");
		buffer.append("dataAggiornamento").append("='")
				.append(getDataAggiornamento()).append("' ");
		buffer.append("fkCodiUtenteAgg").append("='")
				.append(getFkCodiUtenteAgg()).append("' ");
		buffer.append("dataAnnullamento").append("='")
				.append(getDataAnnullamento()).append("' ");
		buffer.append("descFilename").append("='").append(getDescFilename())
				.append("' ");
		buffer.append("codiGuidFascicolo").append("='")
				.append(getCodiGuidFascicolo()).append("' ");
		buffer.append("codiMimeTypeOrig").append("='")
				.append(getCodiMimeTypeOrig()).append("' ");
		buffer.append("codiHash").append("='").append(getCodiHash())
				.append("' ");
		buffer.append("textDescrizione").append("='").append(getTextDescrizione())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DocumentiBO other = (DocumentiBO) obj;
		if (anagAmminDem == null) {
			if (other.anagAmminDem != null)
				return false;
		} else if (!anagAmminDem.equals(other.anagAmminDem))
			return false;
		if (anagMetodoFirma == null) {
			if (other.anagMetodoFirma != null)
				return false;
		} else if (!anagMetodoFirma.equals(other.anagMetodoFirma))
			return false;
		if (anagRagionerieDem == null) {
			if (other.anagRagionerieDem != null)
				return false;
		} else if (!anagRagionerieDem.equals(other.anagRagionerieDem))
			return false;
		if (codiGuidDocumento == null) {
			if (other.codiGuidDocumento != null)
				return false;
		} else if (!codiGuidDocumento.equals(other.codiGuidDocumento))
			return false;
		if (codiGuidDocumentoOrig == null) {
			if (other.codiGuidDocumentoOrig != null)
				return false;
		} else if (!codiGuidDocumentoOrig.equals(other.codiGuidDocumentoOrig))
			return false;
		if (codiGuidFascicolo == null) {
			if (other.codiGuidFascicolo != null)
				return false;
		} else if (!codiGuidFascicolo.equals(other.codiGuidFascicolo))
			return false;
		if (codiHash == null) {
			if (other.codiHash != null)
				return false;
		} else if (!codiHash.equals(other.codiHash))
			return false;
		if (codiMimeTypeOrig == null) {
			if (other.codiMimeTypeOrig != null)
				return false;
		} else if (!codiMimeTypeOrig.equals(other.codiMimeTypeOrig))
			return false;
		if (codiProtocollo == null) {
			if (other.codiProtocollo != null)
				return false;
		} else if (!codiProtocollo.equals(other.codiProtocollo))
			return false;
		if (dataAggiornamento == null) {
			if (other.dataAggiornamento != null)
				return false;
		} else if (!dataAggiornamento.equals(other.dataAggiornamento))
			return false;
		if (dataAnnullamento == null) {
			if (other.dataAnnullamento != null)
				return false;
		} else if (!dataAnnullamento.equals(other.dataAnnullamento))
			return false;
		if (dataArrivo == null) {
			if (other.dataArrivo != null)
				return false;
		} else if (!dataArrivo.equals(other.dataArrivo))
			return false;
		if (dataChiusura == null) {
			if (other.dataChiusura != null)
				return false;
		} else if (!dataChiusura.equals(other.dataChiusura))
			return false;
		if (dataDocumento == null) {
			if (other.dataDocumento != null)
				return false;
		} else if (!dataDocumento.equals(other.dataDocumento))
			return false;
		if (dataProtocollo == null) {
			if (other.dataProtocollo != null)
				return false;
		} else if (!dataProtocollo.equals(other.dataProtocollo))
			return false;
		if (descDocumento == null) {
			if (other.descDocumento != null)
				return false;
		} else if (!descDocumento.equals(other.descDocumento))
			return false;
		if (descFilename == null) {
			if (other.descFilename != null)
				return false;
		} else if (!descFilename.equals(other.descFilename))
			return false;
		if (descTipoFlusso == null) {
			if (other.descTipoFlusso != null)
				return false;
		} else if (!descTipoFlusso.equals(other.descTipoFlusso))
			return false;
		if (descTipoProtocollo == null) {
			if (other.descTipoProtocollo != null)
				return false;
		} else if (!descTipoProtocollo.equals(other.descTipoProtocollo))
			return false;
		if (fascicoli == null) {
			if (other.fascicoli != null)
				return false;
		} else if (!fascicoli.equals(other.fascicoli))
			return false;
		if (fkCodiUtenteAgg == null) {
			if (other.fkCodiUtenteAgg != null)
				return false;
		} else if (!fkCodiUtenteAgg.equals(other.fkCodiUtenteAgg))
			return false;
		if (flagVisibilitaCdc01 == null) {
			if (other.flagVisibilitaCdc01 != null)
				return false;
		} else if (!flagVisibilitaCdc01.equals(other.flagVisibilitaCdc01))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (numeProtocollo == null) {
			if (other.numeProtocollo != null)
				return false;
		} else if (!numeProtocollo.equals(other.numeProtocollo))
			return false;
		if (numeTicketConservazione == null) {
			if (other.numeTicketConservazione != null)
				return false;
		} else if (!numeTicketConservazione
				.equals(other.numeTicketConservazione))
			return false;
		if (numeTitolo == null) {
			if (other.numeTitolo != null)
				return false;
		} else if (!numeTitolo.equals(other.numeTitolo))
			return false;
		if (statConversione == null) {
			if (other.statConversione != null)
				return false;
		} else if (!statConversione.equals(other.statConversione))
			return false;
		if (statDocumento == null) {
			if (other.statDocumento != null)
				return false;
		} else if (!statDocumento.equals(other.statDocumento))
			return false;
		if (statEsitoConversione == null) {
			if (other.statEsitoConversione != null)
				return false;
		} else if (!statEsitoConversione.equals(other.statEsitoConversione))
			return false;
		if (textDescrizione == null) {
			if (other.textDescrizione != null)
				return false;
		} else if (!textDescrizione.equals(other.textDescrizione))
			return false;
		if (tipoDocumento == null) {
			if (other.tipoDocumento != null)
				return false;
		} else if (!tipoDocumento.equals(other.tipoDocumento))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((anagAmminDem == null) ? 0 : anagAmminDem.hashCode());
		result = prime * result
				+ ((anagMetodoFirma == null) ? 0 : anagMetodoFirma.hashCode());
		result = prime
				* result
				+ ((anagRagionerieDem == null) ? 0 : anagRagionerieDem
						.hashCode());
		result = prime
				* result
				+ ((codiGuidDocumento == null) ? 0 : codiGuidDocumento
						.hashCode());
		result = prime
				* result
				+ ((codiGuidDocumentoOrig == null) ? 0 : codiGuidDocumentoOrig
						.hashCode());
		result = prime
				* result
				+ ((codiGuidFascicolo == null) ? 0 : codiGuidFascicolo
						.hashCode());
		result = prime * result
				+ ((codiHash == null) ? 0 : codiHash.hashCode());
		result = prime
				* result
				+ ((codiMimeTypeOrig == null) ? 0 : codiMimeTypeOrig.hashCode());
		result = prime * result
				+ ((codiProtocollo == null) ? 0 : codiProtocollo.hashCode());
		result = prime
				* result
				+ ((dataAggiornamento == null) ? 0 : dataAggiornamento
						.hashCode());
		result = prime
				* result
				+ ((dataAnnullamento == null) ? 0 : dataAnnullamento.hashCode());
		result = prime * result
				+ ((dataArrivo == null) ? 0 : dataArrivo.hashCode());
		result = prime * result
				+ ((dataChiusura == null) ? 0 : dataChiusura.hashCode());
		result = prime * result
				+ ((dataDocumento == null) ? 0 : dataDocumento.hashCode());
		result = prime * result
				+ ((dataProtocollo == null) ? 0 : dataProtocollo.hashCode());
		result = prime * result
				+ ((descDocumento == null) ? 0 : descDocumento.hashCode());
		result = prime * result
				+ ((descFilename == null) ? 0 : descFilename.hashCode());
		result = prime * result
				+ ((descTipoFlusso == null) ? 0 : descTipoFlusso.hashCode());
		result = prime
				* result
				+ ((descTipoProtocollo == null) ? 0 : descTipoProtocollo
						.hashCode());
		result = prime * result
				+ ((fascicoli == null) ? 0 : fascicoli.hashCode());
		result = prime * result
				+ ((fkCodiUtenteAgg == null) ? 0 : fkCodiUtenteAgg.hashCode());
		result = prime
				* result
				+ ((flagVisibilitaCdc01 == null) ? 0 : flagVisibilitaCdc01
						.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((numeProtocollo == null) ? 0 : numeProtocollo.hashCode());
		result = prime
				* result
				+ ((numeTicketConservazione == null) ? 0
						: numeTicketConservazione.hashCode());
		result = prime * result
				+ ((numeTitolo == null) ? 0 : numeTitolo.hashCode());
		result = prime * result
				+ ((statConversione == null) ? 0 : statConversione.hashCode());
		result = prime * result
				+ ((statDocumento == null) ? 0 : statDocumento.hashCode());
		result = prime
				* result
				+ ((statEsitoConversione == null) ? 0 : statEsitoConversione
						.hashCode());
		result = prime * result
				+ ((textDescrizione == null) ? 0 : textDescrizione.hashCode());
		result = prime * result
				+ ((tipoDocumento == null) ? 0 : tipoDocumento.hashCode());
		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
