package it.almavivaitalia.bilancio.commons.bo;

// Generated 23-lug-2015 10.39.39 by Hibernate Tools 3.4.0.CR1

/**
 * DocumentiRedBOId generated by hbm2java
 */
public class DocumentiRedBOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7744121290496304687L;
	private Long fkNumeIdFascicolo;
	private String codiGuidDocumento;

	public DocumentiRedBOId() {
	}

	public DocumentiRedBOId(Long fkNumeIdFascicolo, String codiGuidDocumento) {
		this.fkNumeIdFascicolo = fkNumeIdFascicolo;
		this.codiGuidDocumento = codiGuidDocumento;
	}

	public Long getFkNumeIdFascicolo() {
		return this.fkNumeIdFascicolo;
	}

	public void setFkNumeIdFascicolo(Long fkNumeIdFascicolo) {
		this.fkNumeIdFascicolo = fkNumeIdFascicolo;
	}

	public String getCodiGuidDocumento() {
		return this.codiGuidDocumento;
	}

	public void setCodiGuidDocumento(String codiGuidDocumento) {
		this.codiGuidDocumento = codiGuidDocumento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentiRedBOId))
			return false;
		DocumentiRedBOId castOther = (DocumentiRedBOId) other;

		return ((this.getFkNumeIdFascicolo() == castOther
				.getFkNumeIdFascicolo()) || (this.getFkNumeIdFascicolo() != null
				&& castOther.getFkNumeIdFascicolo() != null && this
				.getFkNumeIdFascicolo()
				.equals(castOther.getFkNumeIdFascicolo())))
				&& ((this.getCodiGuidDocumento() == castOther
						.getCodiGuidDocumento()) || (this
						.getCodiGuidDocumento() != null
						&& castOther.getCodiGuidDocumento() != null && this
						.getCodiGuidDocumento().equals(
								castOther.getCodiGuidDocumento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFkNumeIdFascicolo() == null ? 0 : this
						.getFkNumeIdFascicolo().hashCode());
		result = 37
				* result
				+ (getCodiGuidDocumento() == null ? 0 : this
						.getCodiGuidDocumento().hashCode());
		return result;
	}

}
