package it.almavivaitalia.bilancio.commons.bo;

// Generated 22-lug-2015 15.41.08 by Hibernate Tools 3.4.0.CR1

/**
 * IterFirmaBO generated by hbm2java
 */
public class IterFirmaBO extends AbstractCommonBO implements
		java.io.Serializable {

	private IterFirmaBOId id;
	private AnagModelliIterBO anagModelliIter;
	private AnagFirmatariBO anagFirmatari;

	public IterFirmaBO() {
	}

	public IterFirmaBO(IterFirmaBOId id, AnagModelliIterBO anagModelliIter,
			AnagFirmatariBO anagFirmatari) {
		this.id = id;
		this.anagModelliIter = anagModelliIter;
		this.anagFirmatari = anagFirmatari;
	}

	public IterFirmaBO(IterFirmaBOId id) {
		this.id = id;
	}

	public IterFirmaBOId getId() {
		return this.id;
	}

	public void setId(IterFirmaBOId id) {
		this.id = id;
	}

	public AnagModelliIterBO getAnagModelliIter() {
		return this.anagModelliIter;
	}

	public void setAnagModelliIter(AnagModelliIterBO anagModelliIter) {
		this.anagModelliIter = anagModelliIter;
	}

	public AnagFirmatariBO getAnagFirmatari() {
		return this.anagFirmatari;
	}

	public void setAnagFirmatari(AnagFirmatariBO anagFirmatari) {
		this.anagFirmatari = anagFirmatari;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("anagModelliIter").append("='")
				.append(getAnagModelliIter()).append("' ");
		buffer.append("anagFirmatari").append("='").append(getAnagFirmatari())
				.append("' ");
		buffer.append("numeVersion").append("='").append(getNumeVersion())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IterFirmaBO))
			return false;
		IterFirmaBO castOther = (IterFirmaBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getAnagModelliIter() == castOther
						.getAnagModelliIter()) || (this.getAnagModelliIter() != null
						&& castOther.getAnagModelliIter() != null && this
						.getAnagModelliIter().equals(
								castOther.getAnagModelliIter())))
				&& ((this.getAnagFirmatari() == castOther.getAnagFirmatari()) || (this
						.getAnagFirmatari() != null
						&& castOther.getAnagFirmatari() != null && this
						.getAnagFirmatari()
						.equals(castOther.getAnagFirmatari())))
				&& ((this.getNumeVersion() == castOther.getNumeVersion()));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getAnagModelliIter() == null ? 0 : this.getAnagModelliIter()
						.hashCode());
		result = 37
				* result
				+ (getAnagFirmatari() == null ? 0 : this.getAnagFirmatari()
						.hashCode());
		result = 37
				* result
				+ (getNumeVersion());
		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
