package it.almavivaitalia.bilancio.commons.bo;

// Generated 22-lug-2015 15.41.08 by Hibernate Tools 3.4.0.CR1

/**
 * IterFirmaBOId generated by hbm2java
 */
public class IterFirmaBOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3191105940504005466L;
	private Short fkSequIdIter;
	private Integer numeOrdine;

	public IterFirmaBOId() {
	}

	public IterFirmaBOId(Short fkSequIdIter, Integer numeOrdine) {
		this.fkSequIdIter = fkSequIdIter;
		this.numeOrdine = numeOrdine;
	}

	public Short getFkSequIdIter() {
		return this.fkSequIdIter;
	}

	public void setFkSequIdIter(Short fkSequIdIter) {
		this.fkSequIdIter = fkSequIdIter;
	}

	public Integer getNumeOrdine() {
		return this.numeOrdine;
	}

	public void setNumeOrdine(Integer numeOrdine) {
		this.numeOrdine = numeOrdine;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IterFirmaBOId))
			return false;
		IterFirmaBOId castOther = (IterFirmaBOId) other;

		return ((this.getFkSequIdIter() == castOther.getFkSequIdIter()) || (this
				.getFkSequIdIter() != null
				&& castOther.getFkSequIdIter() != null && this
				.getFkSequIdIter().equals(castOther.getFkSequIdIter())))
				&& ((this.getNumeOrdine() == castOther.getNumeOrdine()) || (this
						.getNumeOrdine() != null
						&& castOther.getNumeOrdine() != null && this
						.getNumeOrdine().equals(castOther.getNumeOrdine())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFkSequIdIter() == null ? 0 : this.getFkSequIdIter()
						.hashCode());
		result = 37
				* result
				+ (getNumeOrdine() == null ? 0 : this.getNumeOrdine()
						.hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "IterFirmaBOId [fkSequIdIter=" + fkSequIdIter + ", numeOrdine="
				+ numeOrdine + "]";
	}
}
