package it.almavivaitalia.bilancio.commons.bo;
// Generated 11-apr-2016 11.37.17 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;

/**
 * LettereTestiPersBOId generated by hbm2java
 */
public class LettereTestiPersBOId  implements java.io.Serializable {


     private BigDecimal fkSequIdLettereIgb;
     private String codiTipoLettera;
     private String codiSezione;
     private Short numeRiga;

    public LettereTestiPersBOId() {
    }

    public LettereTestiPersBOId(BigDecimal fkSequIdLettereIgb, String codiTipoLettera, String codiSezione, Short numeRiga) {
       this.fkSequIdLettereIgb = fkSequIdLettereIgb;
       this.codiTipoLettera = codiTipoLettera;
       this.codiSezione = codiSezione;
       this.numeRiga = numeRiga;
    }
   
    public BigDecimal getFkSequIdLettereIgb() {
        return this.fkSequIdLettereIgb;
    }
    
    public void setFkSequIdLettereIgb(BigDecimal fkSequIdLettereIgb) {
        this.fkSequIdLettereIgb = fkSequIdLettereIgb;
    }
    public String getCodiTipoLettera() {
        return this.codiTipoLettera;
    }
    
    public void setCodiTipoLettera(String codiTipoLettera) {
        this.codiTipoLettera = codiTipoLettera;
    }
    public String getCodiSezione() {
        return this.codiSezione;
    }
    
    public void setCodiSezione(String codiSezione) {
        this.codiSezione = codiSezione;
    }
    public Short getNumeRiga() {
        return this.numeRiga;
    }
    
    public void setNumeRiga(Short numeRiga) {
        this.numeRiga = numeRiga;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LettereTestiPersBOId) ) return false;
		 LettereTestiPersBOId castOther = ( LettereTestiPersBOId ) other; 
         
		 return ( (this.getFkSequIdLettereIgb()==castOther.getFkSequIdLettereIgb()) || ( this.getFkSequIdLettereIgb()!=null && castOther.getFkSequIdLettereIgb()!=null && this.getFkSequIdLettereIgb().equals(castOther.getFkSequIdLettereIgb()) ) )
 && ( (this.getCodiTipoLettera()==castOther.getCodiTipoLettera()) || ( this.getCodiTipoLettera()!=null && castOther.getCodiTipoLettera()!=null && this.getCodiTipoLettera().equals(castOther.getCodiTipoLettera()) ) )
 && ( (this.getCodiSezione()==castOther.getCodiSezione()) || ( this.getCodiSezione()!=null && castOther.getCodiSezione()!=null && this.getCodiSezione().equals(castOther.getCodiSezione()) ) )
 && ( (this.getNumeRiga()==castOther.getNumeRiga()) || ( this.getNumeRiga()!=null && castOther.getNumeRiga()!=null && this.getNumeRiga().equals(castOther.getNumeRiga()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFkSequIdLettereIgb() == null ? 0 : this.getFkSequIdLettereIgb().hashCode() );
         result = 37 * result + ( getCodiTipoLettera() == null ? 0 : this.getCodiTipoLettera().hashCode() );
         result = 37 * result + ( getCodiSezione() == null ? 0 : this.getCodiSezione().hashCode() );
         result = 37 * result + ( getNumeRiga() == null ? 0 : this.getNumeRiga().hashCode() );
         return result;
   }   


}


