package it.almavivaitalia.bilancio.commons.bo;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1

/**
 * TabServDemBOId generated by hbm2java
 */
public class TabServDemBOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5497959216660284460L;
	private Short numeAggr;
	private String codiParametro;
	private String codiValore;

	public TabServDemBOId() {
	}

	public TabServDemBOId(Short numeAggr, String codiParametro,
			String codiValore) {
		this.numeAggr = numeAggr;
		this.codiParametro = codiParametro;
		this.codiValore = codiValore;
	}

	public Short getNumeAggr() {
		return this.numeAggr;
	}

	public void setNumeAggr(Short numeAggr) {
		this.numeAggr = numeAggr;
	}

	public String getCodiParametro() {
		return this.codiParametro;
	}

	public void setCodiParametro(String codiParametro) {
		this.codiParametro = codiParametro;
	}

	public String getCodiValore() {
		return this.codiValore;
	}

	public void setCodiValore(String codiValore) {
		this.codiValore = codiValore;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TabServDemBOId))
			return false;
		TabServDemBOId castOther = (TabServDemBOId) other;

		return ((this.getNumeAggr() == castOther.getNumeAggr()) || (this
				.getNumeAggr() != null && castOther.getNumeAggr() != null && this
				.getNumeAggr().equals(castOther.getNumeAggr())))
				&& ((this.getCodiParametro() == castOther.getCodiParametro()) || (this
						.getCodiParametro() != null
						&& castOther.getCodiParametro() != null && this
						.getCodiParametro()
						.equals(castOther.getCodiParametro())))
				&& ((this.getCodiValore() == castOther.getCodiValore()) || (this
						.getCodiValore() != null
						&& castOther.getCodiValore() != null && this
						.getCodiValore().equals(castOther.getCodiValore())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNumeAggr() == null ? 0 : this.getNumeAggr().hashCode());
		result = 37
				* result
				+ (getCodiParametro() == null ? 0 : this.getCodiParametro()
						.hashCode());
		result = 37
				* result
				+ (getCodiValore() == null ? 0 : this.getCodiValore()
						.hashCode());
		return result;
	}

}
