package it.almavivaitalia.bilancio.commons.bo;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1

/**
 * TabServDemBO generated by hbm2java
 */
public class TabServDemBO extends AbstractCommonBO implements
		java.io.Serializable {

	private TabServDemBOId id;

	public TabServDemBO() {
	}

	public TabServDemBO(TabServDemBOId id) {
		this.id = id;
	}

	public TabServDemBOId getId() {
		return this.id;
	}

	public void setId(TabServDemBOId id) {
		this.id = id;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TabServDemBO))
			return false;
		TabServDemBO castOther = (TabServDemBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
