package it.almavivaitalia.bilancio.commons.bo;
// Generated 11-apr-2016 11.37.17 by Hibernate Tools 3.4.0.CR1



/**
 * LettereTestiPersBO generated by hbm2java
 */
public class LettereTestiPersBO extends AbstractCommonBO implements java.io.Serializable {


     private LettereTestiPersBOId id;
     private FascicoliBO fascicoli;
     private LettereIgbBO lettereIgb;
     private String textContenuto;

    public LettereTestiPersBO() {
    }

	
    public LettereTestiPersBO(LettereTestiPersBOId id, FascicoliBO fascicoli, LettereIgbBO lettereIgb) {
        this.id = id;
        this.fascicoli = fascicoli;
        this.lettereIgb = lettereIgb;
    }
    public LettereTestiPersBO(LettereTestiPersBOId id, FascicoliBO fascicoli, LettereIgbBO lettereIgb, String textContenuto) {
       this.id = id;
       this.fascicoli = fascicoli;
       this.lettereIgb = lettereIgb;
       this.textContenuto = textContenuto;
    }
   
    public LettereTestiPersBOId getId() {
        return this.id;
    }
    
    public void setId(LettereTestiPersBOId id) {
        this.id = id;
    }
    public FascicoliBO getFascicoli() {
        return this.fascicoli;
    }
    
    public void setFascicoli(FascicoliBO fascicoli) {
        this.fascicoli = fascicoli;
    }
    public LettereIgbBO getLettereIgb() {
        return this.lettereIgb;
    }
    
    public void setLettereIgb(LettereIgbBO lettereIgb) {
        this.lettereIgb = lettereIgb;
    }
    public String getTextContenuto() {
        return this.textContenuto;
    }
    
    public void setTextContenuto(String textContenuto) {
        this.textContenuto = textContenuto;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("fascicoli").append("='").append(getFascicoli()).append("' ");			
      buffer.append("lettereIgb").append("='").append(getLettereIgb()).append("' ");			
      buffer.append("textContenuto").append("='").append(getTextContenuto()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LettereTestiPersBO) ) return false;
		 LettereTestiPersBO castOther = ( LettereTestiPersBO ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getFascicoli()==castOther.getFascicoli()) || ( this.getFascicoli()!=null && castOther.getFascicoli()!=null && this.getFascicoli().equals(castOther.getFascicoli()) ) )
 && ( (this.getLettereIgb()==castOther.getLettereIgb()) || ( this.getLettereIgb()!=null && castOther.getLettereIgb()!=null && this.getLettereIgb().equals(castOther.getLettereIgb()) ) )
 && ( (this.getTextContenuto()==castOther.getTextContenuto()) || ( this.getTextContenuto()!=null && castOther.getTextContenuto()!=null && this.getTextContenuto().equals(castOther.getTextContenuto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getFascicoli() == null ? 0 : this.getFascicoli().hashCode() );
         result = 37 * result + ( getLettereIgb() == null ? 0 : this.getLettereIgb().hashCode() );
         result = 37 * result + ( getTextContenuto() == null ? 0 : this.getTextContenuto().hashCode() );
         return result;
   }   

  // The following is extra code specified in the hbm.xml files
private static final long serialVersionUID = 1L;
  // end of extra code specified in the hbm.xml files

}


