package it.almavivaitalia.bilancio.commons.bo;

import it.almavivaitalia.bsn.sh.bo.AbstractBO;

// Generated 6-mag-2015 15.33.00 by Hibernate Tools 3.4.0.CR1

/**
 * StatoFascicoloBO generated by hbm2java
 */
public class StatoFascicoloBO extends AbstractBO implements
		java.io.Serializable {

	private String id;
	private String descStato;

	public StatoFascicoloBO() {
	}

	public StatoFascicoloBO(String descStato) {
		this.descStato = descStato;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDescStato() {
		return this.descStato;
	}

	public void setDescStato(String descStato) {
		this.descStato = descStato;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("descStato").append("='").append(getDescStato())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StatoFascicoloBO))
			return false;
		StatoFascicoloBO castOther = (StatoFascicoloBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getDescStato() == castOther.getDescStato()) || (this
						.getDescStato() != null
						&& castOther.getDescStato() != null && this
						.getDescStato().equals(castOther.getDescStato())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getDescStato() == null ? 0 : this.getDescStato().hashCode());
		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
