package it.almavivaitalia.bilancio.commons.bo;

// Generated 11-ago-2015 10.58.32 by Hibernate Tools 3.4.0.CR1

/**
 * AmminRagDemBO generated by hbm2java
 */
public class AmminRagDemBO extends AbstractCommonBO implements
		java.io.Serializable {

	private AmminRagDemBOId id;

	public AmminRagDemBO() {
	}

	public AmminRagDemBO(AmminRagDemBOId id) {
		this.id = id;
	}

	public AmminRagDemBOId getId() {
		return this.id;
	}

	public void setId(AmminRagDemBOId id) {
		this.id = id;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AmminRagDemBO))
			return false;
		AmminRagDemBO castOther = (AmminRagDemBO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
