package it.mef.bilancio.demdec.to;

// Generated 7-set-2010 11.52.15 by Hibernate Tools 3.2.4.GA

import java.io.Serializable;

/**
 * ApplicationTO generated by hbm2java
 */
public class CronologicoValoriTO extends AbstractDemTO implements Serializable  {//INIZIO METODO
	private static final long serialVersionUID = 1L;
	
	
    private String  campo;
    private String  textOldVal;    
    private String  textNewVal;    
    private String  modificato;
	public String getCampo() {//INIZIO METODO
		return campo;
	}//FINE METODO
	public void setCampo(String campo) {//INIZIO METODO
		this.campo = campo;
	}//FINE METODO
	public String getTextOldVal() {//INIZIO METODO
		return textOldVal;
	}//FINE METODO
	public void setTextOldVal(String textOldVal) {//INIZIO METODO
		this.textOldVal = textOldVal;
	}//FINE METODO
	public String getTextNewVal() {//INIZIO METODO
		return textNewVal;
	}//FINE METODO
	public void setTextNewVal(String textNewVal) {//INIZIO METODO
		this.textNewVal = textNewVal;
	}//FINE METODO
	public String getModificato() {//INIZIO METODO
		return modificato;
	}//FINE METODO
	public void setModificato(String modificato) {//INIZIO METODO
		this.modificato = modificato;
	}//FINE METODO
	public static long getSerialversionuid() {//INIZIO METODO
		return serialVersionUID;
	}//FINE METODO    
            
    
}//FINE METODO
