package it.almavivaitalia.bilancio.commons.to;




/**
 * Utente generated by hbm2java
 */
public class SecurityTO extends AbstractCommonTO implements java.io.Serializable {//INIZIO METODO
	private String utenteSb;
    private String pswdSb;
    private String codiUtenteSbfj;
    private String dataCollegamento;


    public SecurityTO() {//INIZIO METODO
    }



 	public String getUtenteSb() {//INIZIO METODO
		return utenteSb;
	}





	public void setUtenteSb(String utenteSb) {//INIZIO METODO
		this.utenteSb = utenteSb;
	}





	public String getPswdSb() {//INIZIO METODO
		return pswdSb;
	}





	public void setPswdSb(String pswdSb) {//INIZIO METODO
		this.pswdSb = pswdSb;
	}







	public String getCodiUtenteSbfj() {//INIZIO METODO
		return codiUtenteSbfj;
	}





	public void setCodiUtenteSbfj(String codiUtenteSbfj) {//INIZIO METODO
		this.codiUtenteSbfj = codiUtenteSbfj;
	}

	
 
    

    /**
     * toString
     * @return String
     */
     public String toString() {//INIZIO METODO
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("utenteSb").append("='").append(getUtenteSb()).append("' ");			
      buffer.append("pwdSb").append("='").append(getPswdSb()).append("' ");	
      buffer.append("dataCollegamento").append("='").append(getDataCollegamento()).append("' ");	
      buffer.append("codiUtenteSbfj").append("='").append(getUtenteSb()).append("' ");	
      buffer.append("]");
      return  buffer.toString();
      
     }

   public String getDataCollegamento() {//INIZIO METODO
		return dataCollegamento;
	}



	public void setDataCollegamento(String dataCollegamento) {//INIZIO METODO
		this.dataCollegamento = dataCollegamento;
	}



public boolean equals(Object other) {//INIZIO METODO
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SecurityTO) ) return false;
		 SecurityTO castOther = ( SecurityTO ) other; 
         
		 return ( (this.getCodiUtenteSbfj()==castOther.getCodiUtenteSbfj()) || ( this.getCodiUtenteSbfj()!=null && castOther.getCodiUtenteSbfj()!=null && this.getCodiUtenteSbfj().equals(castOther.getCodiUtenteSbfj()) ) )
		 && ( (this. getUtenteSb()==castOther. getUtenteSb()) || ( this. getUtenteSb()!=null && castOther. getUtenteSb()!=null && this. getUtenteSb().equals(castOther. getUtenteSb()) ) );
    }
   
   public int hashCode() {//INIZIO METODO
         int result = 17;
         
         result = 37 * result + ( getCodiUtenteSbfj() == null ? 0 : this.getCodiUtenteSbfj().hashCode() );
         result = 37 * result + ( getUtenteSb() == null ? 0 : this.getUtenteSb().hashCode() );
         
         
         
         return result;
   }   

  // The following is extra code specified in the hbm.xml files
private static final long serialVersionUID = 1L;
  // end of extra code specified in the hbm.xml files

}


