package it.almavivaitalia.bilancio.commons.to;





/**
 * Utente generated by hbm2java
 */
public class UserInfoTO extends AbstractCommonTO implements java.io.Serializable {//INIZIO METODO
	 	
 	 private UtenteTO utenteTO;
	 private SecurityTO securityTO;
	 private Short esercizioFormazione;
	 private Short esercizioGestione;



    public UserInfoTO() {//INIZIO METODO
    }

	
 
     /**
     * toString
     * @return String
     */
     public String toString() {//INIZIO METODO
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("SecurityUtenteTO").append("='").append(getSecurityTO().toString()).append("' ");			
      buffer.append("UtenteTO").append("='").append(getUtenteTO().toString()).append("' ");			
     buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {//INIZIO METODO
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserInfoTO) ) return false;
		 UserInfoTO castOther = ( UserInfoTO ) other; 
         
			return (this.getSecurityTO().equals(castOther.getSecurityTO()));
   }
   
   public int hashCode() {//INIZIO METODO
         int result = 17;
         
 		result = 37 * result + (getUtenteTO() == null ? 0 : this.getUtenteTO().hashCode());
          return result;
   }   

  // The following is extra code specified in the hbm.xml files
private static final long serialVersionUID = 1L;
  // end of extra code specified in the hbm.xml files

public UtenteTO getUtenteTO() {//INIZIO METODO
	return utenteTO;
}

public void setUtenteTO(UtenteTO utenteTO) {//INIZIO METODO
	this.utenteTO = utenteTO;
}

public SecurityTO getSecurityTO() {//INIZIO METODO
	return securityTO;
}

public void setSecurityTO(SecurityTO securityTO) {//INIZIO METODO
	this.securityTO = securityTO;
}



public Short getEsercizioFormazione() {//INIZIO METODO
	return esercizioFormazione;
}



public void setEsercizioFormazione(Short esercizioFormazione) {//INIZIO METODO
	this.esercizioFormazione = esercizioFormazione;
}



public Short getEsercizioGestione() {//INIZIO METODO
	return esercizioGestione;
}



public void setEsercizioGestione(Short esercizioGestione) {//INIZIO METODO
	this.esercizioGestione = esercizioGestione;
}




}


