package it.mef.bilancio.demdec.to;

import it.almavivaitalia.bilancio.commons.to.AbstractCommonTO;

// Generated 1-lug-2015 10.26.47 by Hibernate Tools 3.4.0.CR1


/**
 * AnagTipologiaDecretoBO generated by hbm2java
 */
public class AnagTipologiaDecretoTO extends AbstractCommonTO implements
		java.io.Serializable {

	private Integer id;
	private AnagModelliIterTO anagModelliIter;
	private AnagTipoDecretoTO anagTipoDecreto;
	private String descTipologia;
	private Integer flagNormativo01;

	public AnagTipologiaDecretoTO() {
	}

	public AnagTipologiaDecretoTO(Integer id) {
		this.id = id;
	}

	public AnagTipologiaDecretoTO(Integer id,
			AnagModelliIterTO anagModelliIter,
			AnagTipoDecretoTO anagTipoDecreto, String descTipologia) {
		this.id = id;
		this.anagModelliIter = anagModelliIter;
		this.anagTipoDecreto = anagTipoDecreto;
		this.descTipologia = descTipologia;
	}

	public AnagTipologiaDecretoTO(Integer id,
			AnagModelliIterTO anagModelliIter,
			AnagTipoDecretoTO anagTipoDecreto, String descTipologia,
			Integer flagNormativo01) {
		this.id = id;
		this.anagModelliIter = anagModelliIter;
		this.anagTipoDecreto = anagTipoDecreto;
		this.descTipologia = descTipologia;
		this.flagNormativo01 = flagNormativo01;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AnagModelliIterTO getAnagModelliIter() {
		return this.anagModelliIter;
	}

	public void setAnagModelliIter(AnagModelliIterTO anagModelliIter) {
		this.anagModelliIter = anagModelliIter;
	}

	public AnagTipoDecretoTO getAnagTipoDecreto() {
		return this.anagTipoDecreto;
	}

	public void setAnagTipoDecreto(AnagTipoDecretoTO anagTipoDecreto) {
		this.anagTipoDecreto = anagTipoDecreto;
	}

	public String getDescTipologia() {
		return this.descTipologia;
	}

	public void setDescTipologia(String descTipologia) {
		this.descTipologia = descTipologia;
	}

	public Integer getFlagNormativo01() {
		return this.flagNormativo01;
	}

	public void setFlagNormativo01(Integer flagNormativo01) {
		this.flagNormativo01 = flagNormativo01;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("anagModelliIter").append("='")
				.append(getAnagModelliIter()).append("' ");
		buffer.append("anagTipoDecreto").append("='")
				.append(getAnagTipoDecreto()).append("' ");
		buffer.append("descTipologia").append("='").append(getDescTipologia())
				.append("' ");
		buffer.append("flagNormativo01").append("='")
				.append(getFlagNormativo01()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnagTipologiaDecretoTO))
			return false;
		AnagTipologiaDecretoTO castOther = (AnagTipologiaDecretoTO) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getAnagModelliIter() == castOther
						.getAnagModelliIter()) || (this.getAnagModelliIter() != null
						&& castOther.getAnagModelliIter() != null && this
						.getAnagModelliIter().equals(
								castOther.getAnagModelliIter())))
				&& ((this.getAnagTipoDecreto() == castOther
						.getAnagTipoDecreto()) || (this.getAnagTipoDecreto() != null
						&& castOther.getAnagTipoDecreto() != null && this
						.getAnagTipoDecreto().equals(
								castOther.getAnagTipoDecreto())))
				&& ((this.getDescTipologia() == castOther.getDescTipologia()) || (this
						.getDescTipologia() != null
						&& castOther.getDescTipologia() != null && this
						.getDescTipologia()
						.equals(castOther.getDescTipologia())))
				&& ((this.getFlagNormativo01() == castOther
						.getFlagNormativo01()) || (this.getFlagNormativo01() != null
						&& castOther.getFlagNormativo01() != null && this
						.getFlagNormativo01().equals(
								castOther.getFlagNormativo01())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getAnagModelliIter() == null ? 0 : this.getAnagModelliIter()
						.hashCode());
		result = 37
				* result
				+ (getAnagTipoDecreto() == null ? 0 : this.getAnagTipoDecreto()
						.hashCode());
		result = 37
				* result
				+ (getDescTipologia() == null ? 0 : this.getDescTipologia()
						.hashCode());
		result = 37
				* result
				+ (getFlagNormativo01() == null ? 0 : this.getFlagNormativo01()
						.hashCode());

		return result;
	}

	// The following is extra code specified in the hbm.xml files
	private static final long serialVersionUID = 1L;
	// end of extra code specified in the hbm.xml files

}
